package com.wiley.gr.ace.auth.security.dao;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alerts generated by hbm2java
 */
@Entity
@Table(name = "ALERTS")
public class Alerts implements java.io.Serializable {

	private String alertCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String alertName;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	private Set<UserAlerts> userAlertses = new HashSet<UserAlerts>(0);

	public Alerts() {
	}

	public Alerts(String alertCd) {
		this.alertCd = alertCd;
	}

	public Alerts(String alertCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String alertName, String description,
			Date createdDate, Date updatedDate, Set<UserAlerts> userAlertses) {
		this.alertCd = alertCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.alertName = alertName;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.userAlertses = userAlertses;
	}

	@Id
	@Column(name = "ALERT_CD", unique = true, nullable = false, length = 15)
	public String getAlertCd() {
		return this.alertCd;
	}

	public void setAlertCd(String alertCd) {
		this.alertCd = alertCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "ALERT_NAME", length = 250)
	public String getAlertName() {
		return this.alertName;
	}

	public void setAlertName(String alertName) {
		this.alertName = alertName;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerts")
	public Set<UserAlerts> getUserAlertses() {
		return this.userAlertses;
	}

	public void setUserAlertses(Set<UserAlerts> userAlertses) {
		this.userAlertses = userAlertses;
	}

}
