/**
 * ****************************************************************************
 * Copyright (c) 2015 John Wiley & Sons, Inc. All rights reserved.
 * <p>
 * All material contained herein is proprietary to John Wiley & Sons
 * and its third party suppliers, if any. The methods, techniques and
 * technical concepts contained herein are considered trade secrets
 * and confidential and may be protected by intellectual property laws.
 * Reproduction or distribution of this material, in whole or in part,
 * is strictly forbidden except by express prior written permission
 * of John Wiley & Sons.
 * *****************************************************************************
 */
package com.wiley.gr.ace.auth.security.dao;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * LockedAccountDetails generated by hbm2java
 *
 * @author Virtusa
 */
@Entity
@Table(name = "LOCKED_ACCOUNT_DETAILS")
public class LockedAccountDetails implements java.io.Serializable {

    /**
     * This field holds the value of userId
     */
    private String userId;

    /**
     * This field holds the value of invalidLoginCount
     */
    private Integer invalidLoginCount;

    /**
     * This field holds the value of lockedTime
     */
    private Date lockedTime;

    /**
     * This field holds the value of appKey
     */
    private String appKey;

    /**
     * This field holds the value of createdBy
     */
    private Integer createdBy;

    /**
     * This field holds the value of createdDate
     */
    private Date createdDate;

    /**
     * This field holds the value of updatedBy
     */
    private Integer updatedBy;

    /**
     * This field holds the value of updatedDate
     */
    private Date updatedDate;

    /**
     * This field holds the value of loginAttemptTime
     */
    private Date loginAttemptTime;

    /**
     * Default constructor
     */
    public LockedAccountDetails() {
    }

    /**
     * Parametered constructor
     *
     * @param userId
     */
    public LockedAccountDetails(final String userId) {
        this.userId = userId;
    }


    /**
     * This method gets the App Key
     *
     * @return String
     */
    @Column(name = "APP_KEY")
    public String getAppKey() {
        return this.appKey;
    }

    public void setAppKey(final String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method gets Created By user
     *
     * @return Integer
     */
    @Column(name = "CREATED_BY", precision = 22, scale = 0)
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(final Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method gets Created Date
     *
     * @return Date
     */
    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }

    /**
     * This method setCreatedDate
     *
     * @param createdDate void
     */
    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method gets Invalid Login Count
     *
     * @return Integer
     */
    @Column(name = "INVALID_LOGIN_COUNT", precision = 22, scale = 0)
    public Integer getInvalidLoginCount() {
        return this.invalidLoginCount;
    }

    public void setInvalidLoginCount(final Integer invalidLoginCount) {
        this.invalidLoginCount = invalidLoginCount;
    }

    /**
     * This method gets Locked Time
     *
     * @return Date
     */
    @Column(name = "LOCKED_TIME")
    public Date getLockedTime() {
        return this.lockedTime;
    }

    public void setLockedTime(final Date lockedTime) {
        this.lockedTime = lockedTime;
    }

    /**
     * This method gets the Login Attempt Time
     *
     * @return Date
     */
    @Column(name = "LOGIN_ATTEMPT_TIME")
    public Date getLoginAttemptTime() {
        return this.loginAttemptTime;
    }

    /**
     * This method setLoginAttemptTime
     *
     * @param loginAttemptTime void
     */
    public void setLoginAttemptTime(final Date loginAttemptTime) {
        this.loginAttemptTime = loginAttemptTime;
    }

    /**
     * This method getUpdatedBy
     *
     * @return Integer
     */
    @Column(name = "UPDATED_BY", precision = 22, scale = 0)
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * This method setUpdatedBy
     *
     * @param updatedBy void
     */
    public void setUpdatedBy(final Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method getUpdatedDate
     *
     * @return Date
     */
    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * This method setUpdatedDate
     *
     * @param updatedDate void
     */
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * Getter method
     *
     * @return String
     */
    @Id
    @Column(name = "USER_ID", unique = true, nullable = false)
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter method to set the userId
     *
     * @param userId void
     */
    public void setUserId(final String userId) {
        this.userId = userId;
    }

}
