/*******************************************************************************
 * Copyright (c) 2015 John Wiley & Sons, Inc. All rights reserved.
 *
 * All material contained herein is proprietary to John Wiley & Sons 
 * and its third party suppliers, if any. The methods, techniques and 
 * technical concepts contained herein are considered trade secrets 
 * and confidential and may be protected by intellectual property laws.  
 * Reproduction or distribution of this material, in whole or in part, 
 * is strictly forbidden except by express prior written permission 
 * of John Wiley & Sons.
 *******************************************************************************/
package com.wiley.gr.ace.auth.security.dao;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LockedAccountDetails generated by hbm2java
 */
@Entity
@Table(name = "LOCKED_ACCOUNT_DETAILS")
public class LockedAccountDetails implements java.io.Serializable {

	private String userId;
	private Integer invalidLoginCount;
	private Date lockedTime;
	private String appKey;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Date loginAttemptTime;

	public LockedAccountDetails() {
	}

	public LockedAccountDetails(String userId) {
		this.userId = userId;
	}

	public LockedAccountDetails(String userId, Integer invalidLoginCount,
			Date lockedTime, String appKey, Integer createdBy,
			Date createdDate, Integer updatedBy, Date updatedDate,
			Date loginAttemptTime) {
		this.userId = userId;
		this.invalidLoginCount = invalidLoginCount;
		this.lockedTime = lockedTime;
		this.appKey = appKey;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.loginAttemptTime = loginAttemptTime;
	}

	@Id
	@Column(name = "USER_ID", unique = true, nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "INVALID_LOGIN_COUNT", precision = 22, scale = 0)
	public Integer getInvalidLoginCount() {
		return this.invalidLoginCount;
	}

	public void setInvalidLoginCount(Integer invalidLoginCount) {
		this.invalidLoginCount = invalidLoginCount;
	}

	@Column(name = "LOCKED_TIME")
	public Date getLockedTime() {
		return this.lockedTime;
	}

	public void setLockedTime(Date lockedTime) {
		this.lockedTime = lockedTime;
	}

	@Column(name = "APP_KEY")
	public String getAppKey() {
		return this.appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_BY", precision = 22, scale = 0)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "LOGIN_ATTEMPT_TIME")
	public Date getLoginAttemptTime() {
		return this.loginAttemptTime;
	}

	public void setLoginAttemptTime(Date loginAttemptTime) {
		this.loginAttemptTime = loginAttemptTime;
	}

}
