package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdditionalPermissions generated by hbm2java
 */
@Entity
@Table(name = "ADDITIONAL_PERMISSIONS")
public class AdditionalPermissions implements java.io.Serializable {

	private Integer additionalPermissionsId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Users usersByUserId;
	private ObjectTypes objectTypes;
	private Permissions permissions;
	private Date permEndDt;
	private Integer objectId;
	private Date createdDate;
	private Date updatedDate;

	public AdditionalPermissions() {
	}

	public AdditionalPermissions(Integer additionalPermissionsId,
			Permissions permissions) {
		this.additionalPermissionsId = additionalPermissionsId;
		this.permissions = permissions;
	}

	public AdditionalPermissions(Integer additionalPermissionsId,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			Users usersByUserId, ObjectTypes objectTypes,
			Permissions permissions, Date permEndDt, Integer objectId,
			Date createdDate, Date updatedDate) {
		this.additionalPermissionsId = additionalPermissionsId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.usersByUserId = usersByUserId;
		this.objectTypes = objectTypes;
		this.permissions = permissions;
		this.permEndDt = permEndDt;
		this.objectId = objectId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "ADDITIONAL_PERMISSIONS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getAdditionalPermissionsId() {
		return this.additionalPermissionsId;
	}

	public void setAdditionalPermissionsId(Integer additionalPermissionsId) {
		this.additionalPermissionsId = additionalPermissionsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OBJECT_TYPE_CD")
	public ObjectTypes getObjectTypes() {
		return this.objectTypes;
	}

	public void setObjectTypes(ObjectTypes objectTypes) {
		this.objectTypes = objectTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSION_CD", nullable = false)
	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	@Column(name = "PERM_END_DT")
	public Date getPermEndDt() {
		return this.permEndDt;
	}

	public void setPermEndDt(Date permEndDt) {
		this.permEndDt = permEndDt;
	}

	@Column(name = "OBJECT_ID", precision = 22, scale = 0)
	public Integer getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
