package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderTypes generated by hbm2java
 */
@Entity
@Table(name = "ORDER_TYPES")
public class OrderTypes implements java.io.Serializable {

	private String orderTypeCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String orderTypeName;
	private Date createdDate;
	private Date updatedDate;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public OrderTypes() {
	}

	public OrderTypes(String orderTypeCd) {
		this.orderTypeCd = orderTypeCd;
	}

	public OrderTypes(String orderTypeCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String orderTypeName, Date createdDate,
			Date updatedDate, Set<Orders> orderses) {
		this.orderTypeCd = orderTypeCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.orderTypeName = orderTypeName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "ORDER_TYPE_CD", unique = true, nullable = false, length = 15)
	public String getOrderTypeCd() {
		return this.orderTypeCd;
	}

	public void setOrderTypeCd(String orderTypeCd) {
		this.orderTypeCd = orderTypeCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "ORDER_TYPE_NAME", length = 250)
	public String getOrderTypeName() {
		return this.orderTypeName;
	}

	public void setOrderTypeName(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderTypes")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
