package com.wiley.gr.ace.authorservices.persistence.entity;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NotificationData generated by hbm2java
 */
@Entity
@Table(name = "NOTIFICATION_DATA")
public class NotificationData implements java.io.Serializable {

	private Integer id;
	private Notification notification;
	private String dataItemKey;
	private String dataItemValue;

	public NotificationData() {
	}

	public NotificationData(Integer id) {
		this.id = id;
	}

	public NotificationData(Integer id, Notification notification,
			String dataItemKey, String dataItemValue) {
		this.id = id;
		this.notification = notification;
		this.dataItemKey = dataItemKey;
		this.dataItemValue = dataItemValue;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NOTIFICATION_DATA_SEQ")
    @SequenceGenerator(name = "NOTIFICATION_DATA_SEQ", sequenceName = "NOTIFICATION_DATA_SEQ", allocationSize = 1)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NOTIFICATION_ID")
	public Notification getNotification() {
		return this.notification;
	}

	public void setNotification(Notification notification) {
		this.notification = notification;
	}

	@Column(name = "DATA_ITEM_KEY")
	public String getDataItemKey() {
		return this.dataItemKey;
	}

	public void setDataItemKey(String dataItemKey) {
		this.dataItemKey = dataItemKey;
	}

	@Column(name = "DATA_ITEM_VALUE")
	public String getDataItemValue() {
		return this.dataItemValue;
	}

	public void setDataItemValue(String dataItemValue) {
		this.dataItemValue = dataItemValue;
	}

}
