package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Aug 11, 2015 2:21:56 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NotificationRecipients generated by hbm2java
 */
@Entity
@Table(name = "NOTIFICATION_RECIPIENTS")
public class NotificationRecipients implements java.io.Serializable {

	private Integer recipientsId;
	private Notification notification;
	private String userId;
	private String email;
	private String type;

	public NotificationRecipients() {
	}

	public NotificationRecipients(final Integer recipientsId) {
		this.recipientsId = recipientsId;
	}

	public NotificationRecipients(final Integer recipientsId,
			final Notification notification, final String userId, final String email, final String type) {
		this.recipientsId = recipientsId;
		this.notification = notification;
		this.userId = userId;
		this.email = email;
		this.type = type;
	}

	@Id
	@Column(name = "RECIPIENTS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NOTIFICATION_RECIPIENTS_SEQ")
    @SequenceGenerator(name = "NOTIFICATION_RECIPIENTS_SEQ", sequenceName = "NOTIFICATION_RECIPIENTS_SEQ", allocationSize = 1)
	public Integer getRecipientsId() {
		return this.recipientsId;
	}

	public void setRecipientsId(final Integer recipientsId) {
		this.recipientsId = recipientsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NOTIFICATION_ID")
	public Notification getNotification() {
		return this.notification;
	}

	public void setNotification(final Notification notification) {
		this.notification = notification;
	}

	@Column(name = "USER_ID")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(final String userId) {
		this.userId = userId;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(final String email) {
		this.email = email;
	}

	@Column(name = "TYPE", length = 25)
	public String getType() {
		return this.type;
	}

	public void setType(final String type) {
		this.type = type;
	}

}
