package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Aug 11, 2015 2:21:56 PM by Hibernate Tools 4.0.0

import java.util.Date;




import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "SCHEDULE")
public class Schedule implements java.io.Serializable {

	private String id;
	private String appId;
	private String description;
	private String createdBy;
	private String modifiedBy;
	private Date createdOn;
	private Date lastModifiedOn;
	private ScheduleTemplate scheduleTemplate;

	public Schedule() {
	}

	public Schedule(String id) {
		this.id = id;
	}

	public Schedule(String id, String appId, String description,
			String createdBy, String modifiedBy, Date createdOn,
			Date lastModifiedOn, ScheduleTemplate scheduleTemplate) {
		this.id = id;
		this.appId = appId;
		this.description = description;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
		this.scheduleTemplate = scheduleTemplate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "APP_ID", length = 25)
	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_ON", length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_MODIFIED_ON", length = 7)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "schedule")
	@Cascade(value = { CascadeType.SAVE_UPDATE,CascadeType.DELETE})
	public ScheduleTemplate getScheduleTemplate() {
		return this.scheduleTemplate;
	}

	public void setScheduleTemplate(ScheduleTemplate scheduleTemplate) {
		this.scheduleTemplate = scheduleTemplate;
	}

}
