/*******************************************************************************
 * Copyright (c) 2015 John Wiley & Sons, Inc. All rights reserved.
 *
 * All material contained herein is proprietary to John Wiley & Sons 
 * and its third party suppliers, if any. The methods, techniques and 
 * technical concepts contained herein are considered trade secrets 
 * and confidential and may be protected by intellectual property laws.  
 * Reproduction or distribution of this material, in whole or in part, 
 * is strictly forbidden except by express prior written permission 
 * of John Wiley & Sons.
 *******************************************************************************/
package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 16, 2015 3:29:29 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * Template generated by hbm2java.
 * 
 * @author virtusa version 1.0
 */
@Entity
@Table(name = "TEMPLATE")
public class Template implements java.io.Serializable {

	/** The id. */
	private String id;
	
	/** The app id. */
	private String appId;
	
	/** The description. */
	private String description;
	
	/** The tagl1. */
	private String tagl1;
	
	/** The tagl2. */
	private String tagl2;
	
	/** The body. */
	private Clob body;
	
	/** The created by. */
	private String createdBy;
	
	/** The modified by. */
	private String modifiedBy;
	
	/** The created on. */
	private Date createdOn;
	
	/** The last modified on. */
	private Date lastModifiedOn;
	
	/** The notifications. */
	private Set<Notification> notifications = new HashSet<Notification>(0);
	
	/** The schedule templates for email tmpl. */
	private Set<ScheduleTemplate> scheduleTemplatesForEmailTmpl = new HashSet<ScheduleTemplate>(
			0);
	
	/** The schedule templates for onscreen tmpl. */
	private Set<ScheduleTemplate> scheduleTemplatesForOnscreenTmpl = new HashSet<ScheduleTemplate>(
			0);

	/**
	 * Instantiates a new template.
	 */
	public Template() {
	}

	/**
	 * Instantiates a new template.
	 *
	 * @param id the id
	 */
	public Template(String id) {
		this.id = id;
	}

	/**
	 * Instantiates a new template.
	 *
	 * @param id the id
	 * @param appId the app id
	 * @param description the description
	 * @param tagl1 the tagl1
	 * @param tagl2 the tagl2
	 * @param body the body
	 * @param createdBy the created by
	 * @param modifiedBy the modified by
	 * @param createdOn the created on
	 * @param lastModifiedOn the last modified on
	 * @param notifications the notifications
	 * @param scheduleTemplatesForEmailTmpl the schedule templates for email tmpl
	 * @param scheduleTemplatesForOnscreenTmpl the schedule templates for onscreen tmpl
	 */
	public Template(String id, String appId, String description, String tagl1,
			String tagl2, Clob body, String createdBy, String modifiedBy,
			Date createdOn, Date lastModifiedOn,
			Set<Notification> notifications,
			Set<ScheduleTemplate> scheduleTemplatesForEmailTmpl,
			Set<ScheduleTemplate> scheduleTemplatesForOnscreenTmpl) {
		this.id = id;
		this.appId = appId;
		this.description = description;
		this.tagl1 = tagl1;
		this.tagl2 = tagl2;
		this.body = body;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.createdOn = createdOn;
		this.lastModifiedOn = lastModifiedOn;
		this.notifications = notifications;
		this.scheduleTemplatesForEmailTmpl = scheduleTemplatesForEmailTmpl;
		this.scheduleTemplatesForOnscreenTmpl = scheduleTemplatesForOnscreenTmpl;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the app id.
	 *
	 * @return the app id
	 */
	@Column(name = "APP_ID", length = 25)
	public String getAppId() {
		return this.appId;
	}

	/**
	 * Sets the app id.
	 *
	 * @param appId the new app id
	 */
	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the tagl1.
	 *
	 * @return the tagl1
	 */
	@Column(name = "TAGL1")
	public String getTagl1() {
		return this.tagl1;
	}

	/**
	 * Sets the tagl1.
	 *
	 * @param tagl1 the new tagl1
	 */
	public void setTagl1(String tagl1) {
		this.tagl1 = tagl1;
	}

	/**
	 * Gets the tagl2.
	 *
	 * @return the tagl2
	 */
	@Column(name = "TAGL2")
	public String getTagl2() {
		return this.tagl2;
	}

	/**
	 * Sets the tagl2.
	 *
	 * @param tagl2 the new tagl2
	 */
	public void setTagl2(String tagl2) {
		this.tagl2 = tagl2;
	}

	/**
	 * Gets the body.
	 *
	 * @return the body
	 */
	@Column(name = "BODY")
	public Clob getBody() {
		return this.body;
	}

	/**
	 * Sets the body.
	 *
	 * @param body the new body
	 */
	public void setBody(Clob body) {
		this.body = body;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the modified by.
	 *
	 * @return the modified by
	 */
	@Column(name = "MODIFIED_BY")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	/**
	 * Sets the modified by.
	 *
	 * @param modifiedBy the new modified by
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * Gets the created on.
	 *
	 * @return the created on
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_ON", length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	/**
	 * Sets the created on.
	 *
	 * @param createdOn the new created on
	 */
	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	/**
	 * Gets the last modified on.
	 *
	 * @return the last modified on
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_MODIFIED_ON", length = 7)
	public Date getLastModifiedOn() {
		return this.lastModifiedOn;
	}

	/**
	 * Sets the last modified on.
	 *
	 * @param lastModifiedOn the new last modified on
	 */
	public void setLastModifiedOn(Date lastModifiedOn) {
		this.lastModifiedOn = lastModifiedOn;
	}

	/**
	 * Gets the notifications.
	 *
	 * @return the notifications
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "template")
	public Set<Notification> getNotifications() {
		return this.notifications;
	}

	/**
	 * Sets the notifications.
	 *
	 * @param notifications the new notifications
	 */
	public void setNotifications(Set<Notification> notifications) {
		this.notifications = notifications;
	}

	/**
	 * Gets the schedule templates for email tmpl.
	 *
	 * @return the schedule templates for email tmpl
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "templateByEmailTmpl")
	public Set<ScheduleTemplate> getScheduleTemplatesForEmailTmpl() {
		return this.scheduleTemplatesForEmailTmpl;
	}

	/**
	 * Sets the schedule templates for email tmpl.
	 *
	 * @param scheduleTemplatesForEmailTmpl the new schedule templates for email tmpl
	 */
	public void setScheduleTemplatesForEmailTmpl(
			Set<ScheduleTemplate> scheduleTemplatesForEmailTmpl) {
		this.scheduleTemplatesForEmailTmpl = scheduleTemplatesForEmailTmpl;
	}

	/**
	 * Gets the schedule templates for onscreen tmpl.
	 *
	 * @return the schedule templates for onscreen tmpl
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "templateByOnscreenTmpl")
	public Set<ScheduleTemplate> getScheduleTemplatesForOnscreenTmpl() {
		return this.scheduleTemplatesForOnscreenTmpl;
	}

	/**
	 * Sets the schedule templates for onscreen tmpl.
	 *
	 * @param scheduleTemplatesForOnscreenTmpl the new schedule templates for onscreen tmpl
	 */
	public void setScheduleTemplatesForOnscreenTmpl(
			Set<ScheduleTemplate> scheduleTemplatesForOnscreenTmpl) {
		this.scheduleTemplatesForOnscreenTmpl = scheduleTemplatesForOnscreenTmpl;
	}

}
