package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AddressType generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS_TYPE")
public class AddressType implements java.io.Serializable {

    private String addressTypeCd;
    private Users usersByCreatedBy;
    private Users usersByUpdatedBy;
    private String name;
    private String description;
    private Date createdDate;
    private Date updatedDate;
    private Set<UserAddresses> userAddresseses = new HashSet<UserAddresses>(0);

    public AddressType() {
    }

    public AddressType(String addressTypeCd) {
        this.addressTypeCd = addressTypeCd;
    }

    public AddressType(String addressTypeCd, Users usersByCreatedBy,
            Users usersByUpdatedBy, String name, String description,
            Date createdDate, Date updatedDate,
            Set<UserAddresses> userAddresseses) {
        this.addressTypeCd = addressTypeCd;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByUpdatedBy = usersByUpdatedBy;
        this.name = name;
        this.description = description;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.userAddresseses = userAddresseses;
    }

    @Id
    @Column(name = "ADDRESS_TYPE_CD", unique = true, nullable = false, length = 15)
    public String getAddressTypeCd() {
        return addressTypeCd;
    }

    public void setAddressTypeCd(String addressTypeCd) {
        this.addressTypeCd = addressTypeCd;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY")
    public Users getUsersByCreatedBy() {
        return usersByCreatedBy;
    }

    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPDATED_BY")
    public Users getUsersByUpdatedBy() {
        return usersByUpdatedBy;
    }

    public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
        this.usersByUpdatedBy = usersByUpdatedBy;
    }

    @Column(name = "NAME", length = 50)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 250)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "addressType")
    public Set<UserAddresses> getUserAddresseses() {
        return userAddresseses;
    }

    public void setUserAddresseses(Set<UserAddresses> userAddresseses) {
        this.userAddresseses = userAddresseses;
    }

}
