package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * AuditDetails generated by hbm2java
 */
@Entity
@Table(name = "AUDIT_DETAILS")
public class AuditDetails implements java.io.Serializable {

    private AuditDetailsId id;
    private Users usersByCreatedBy;
    private Users usersByUserId;

    public AuditDetails() {
    }

    public AuditDetails(AuditDetailsId id) {
        this.id = id;
    }

    public AuditDetails(AuditDetailsId id, Users usersByCreatedBy,
                        Users usersByUserId) {
        this.id = id;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByUserId = usersByUserId;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "auditId", column = @Column(name = "AUDIT_ID", precision = 22, scale = 0)),
            @AttributeOverride(name = "objName", column = @Column(name = "OBJ_NAME", length = 50)),
            @AttributeOverride(name = "objAttribute", column = @Column(name = "OBJ_ATTRIBUTE", length = 50)),
            @AttributeOverride(name = "actionCd", column = @Column(name = "ACTION_CD", length = 15)),
            @AttributeOverride(name = "oldVal", column = @Column(name = "OLD_VAL", length = 250)),
            @AttributeOverride(name = "newVal", column = @Column(name = "NEW_VAL", length = 250)),
            @AttributeOverride(name = "userId", column = @Column(name = "USER_ID", precision = 22, scale = 0)),
            @AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
            @AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", precision = 22, scale = 0))})
    public AuditDetailsId getId() {
        return this.id;
    }

    public void setId(AuditDetailsId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY", insertable = false, updatable = false)
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }

    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID", insertable = false, updatable = false)
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }

    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }

}
