package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatabasechangelogId generated by hbm2java
 */
@Embeddable
public class DatabasechangelogId implements java.io.Serializable {

    private String id;
    private String author;
    private String filename;
    private Date dateexecuted;
    private Integer orderexecuted;
    private String exectype;
    private String md5sum;
    private String description;
    private String comments;
    private String tag;
    private String liquibase;

    public DatabasechangelogId() {
    }

    public DatabasechangelogId(String id, String author, String filename,
            Date dateexecuted, Integer orderexecuted, String exectype) {
        this.id = id;
        this.author = author;
        this.filename = filename;
        this.dateexecuted = dateexecuted;
        this.orderexecuted = orderexecuted;
        this.exectype = exectype;
    }

    public DatabasechangelogId(String id, String author, String filename,
            Date dateexecuted, Integer orderexecuted, String exectype,
            String md5sum, String description, String comments, String tag,
            String liquibase) {
        this.id = id;
        this.author = author;
        this.filename = filename;
        this.dateexecuted = dateexecuted;
        this.orderexecuted = orderexecuted;
        this.exectype = exectype;
        this.md5sum = md5sum;
        this.description = description;
        this.comments = comments;
        this.tag = tag;
        this.liquibase = liquibase;
    }

    @Column(name = "ID", nullable = false)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "AUTHOR", nullable = false)
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name = "FILENAME", nullable = false)
    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name = "DATEEXECUTED", nullable = false)
    public Date getDateexecuted() {
        return dateexecuted;
    }

    public void setDateexecuted(Date dateexecuted) {
        this.dateexecuted = dateexecuted;
    }

    @Column(name = "ORDEREXECUTED", nullable = false, precision = 10, scale = 0)
    public Integer getOrderexecuted() {
        return orderexecuted;
    }

    public void setOrderexecuted(Integer orderexecuted) {
        this.orderexecuted = orderexecuted;
    }

    @Column(name = "EXECTYPE", nullable = false, length = 10)
    public String getExectype() {
        return exectype;
    }

    public void setExectype(String exectype) {
        this.exectype = exectype;
    }

    @Column(name = "MD5SUM", length = 35)
    public String getMd5sum() {
        return md5sum;
    }

    public void setMd5sum(String md5sum) {
        this.md5sum = md5sum;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "COMMENTS")
    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "TAG")
    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    @Column(name = "LIQUIBASE", length = 20)
    public String getLiquibase() {
        return liquibase;
    }

    public void setLiquibase(String liquibase) {
        this.liquibase = liquibase;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof DatabasechangelogId)) {
            return false;
        }
        final DatabasechangelogId castOther = (DatabasechangelogId) other;

        return (getId() == castOther.getId() || getId() != null
                && castOther.getId() != null
                && getId().equals(castOther.getId()))
                && (getAuthor() == castOther.getAuthor() || getAuthor() != null
                        && castOther.getAuthor() != null
                        && getAuthor().equals(castOther.getAuthor()))
                && (getFilename() == castOther.getFilename() || getFilename() != null
                        && castOther.getFilename() != null
                        && getFilename().equals(castOther.getFilename()))
                && (getDateexecuted() == castOther.getDateexecuted() || getDateexecuted() != null
                        && castOther.getDateexecuted() != null
                        && getDateexecuted()
                                .equals(castOther.getDateexecuted()))
                && (getOrderexecuted() == castOther.getOrderexecuted() || getOrderexecuted() != null
                        && castOther.getOrderexecuted() != null
                        && getOrderexecuted().equals(
                                castOther.getOrderexecuted()))
                && (getExectype() == castOther.getExectype() || getExectype() != null
                        && castOther.getExectype() != null
                        && getExectype().equals(castOther.getExectype()))
                && (getMd5sum() == castOther.getMd5sum() || getMd5sum() != null
                        && castOther.getMd5sum() != null
                        && getMd5sum().equals(castOther.getMd5sum()))
                && (getDescription() == castOther.getDescription() || getDescription() != null
                        && castOther.getDescription() != null
                        && getDescription().equals(castOther.getDescription()))
                && (getComments() == castOther.getComments() || getComments() != null
                        && castOther.getComments() != null
                        && getComments().equals(castOther.getComments()))
                && (getTag() == castOther.getTag() || getTag() != null
                        && castOther.getTag() != null
                        && getTag().equals(castOther.getTag()))
                && (getLiquibase() == castOther.getLiquibase() || getLiquibase() != null
                        && castOther.getLiquibase() != null
                        && getLiquibase().equals(castOther.getLiquibase()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : getId().hashCode());
        result = 37 * result
                + (getAuthor() == null ? 0 : getAuthor().hashCode());
        result = 37 * result
                + (getFilename() == null ? 0 : getFilename().hashCode());
        result = 37
                * result
                + (getDateexecuted() == null ? 0 : getDateexecuted().hashCode());
        result = 37
                * result
                + (getOrderexecuted() == null ? 0 : getOrderexecuted()
                        .hashCode());
        result = 37 * result
                + (getExectype() == null ? 0 : getExectype().hashCode());
        result = 37 * result
                + (getMd5sum() == null ? 0 : getMd5sum().hashCode());
        result = 37 * result
                + (getDescription() == null ? 0 : getDescription().hashCode());
        result = 37 * result
                + (getComments() == null ? 0 : getComments().hashCode());
        result = 37 * result + (getTag() == null ? 0 : getTag().hashCode());
        result = 37 * result
                + (getLiquibase() == null ? 0 : getLiquibase().hashCode());
        return result;
    }

}
