package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Databasechangeloglock generated by hbm2java
 */
@Entity
@Table(name = "DATABASECHANGELOGLOCK")
public class Databasechangeloglock implements java.io.Serializable {

    private Integer id;
    private Integer locked;
    private Date lockgranted;
    private String lockedby;

    public Databasechangeloglock() {
    }

    public Databasechangeloglock(Integer id, Integer locked) {
        this.id = id;
        this.locked = locked;
    }

    public Databasechangeloglock(Integer id, Integer locked, Date lockgranted,
            String lockedby) {
        this.id = id;
        this.locked = locked;
        this.lockgranted = lockgranted;
        this.lockedby = lockedby;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "LOCKED", nullable = false, precision = 1, scale = 0)
    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    @Column(name = "LOCKGRANTED")
    public Date getLockgranted() {
        return lockgranted;
    }

    public void setLockgranted(Date lockgranted) {
        this.lockgranted = lockgranted;
    }

    @Column(name = "LOCKEDBY")
    public String getLockedby() {
        return lockedby;
    }

    public void setLockedby(String lockedby) {
        this.lockedby = lockedby;
    }

}
