package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 27, 2015 4:45:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InviteResetpwdLog generated by hbm2java
 */
@Entity
@Table(name = "INVITE_RESETPWD_LOG")
public class InviteResetpwdLog implements java.io.Serializable {

    private String guid;
    private String firstName;
    private String lastName;
    private String emailAddress;
    private String userType;
    private String status;

    public InviteResetpwdLog() {
    }

    public InviteResetpwdLog(String guid, String emailAddress) {
        this.guid = guid;
        this.emailAddress = emailAddress;
    }

    public InviteResetpwdLog(String guid, String firstName, String lastName,
                             String emailAddress, String userType, String status) {
        this.guid = guid;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.userType = userType;
        this.status = status;
    }

    @Id
    @Column(name = "GUID", unique = true, nullable = false, length = 200)
    public String getGuid() {
        return this.guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    @Column(name = "FIRST_NAME", length = 200)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "LAST_NAME", length = 200)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "EMAIL_ADDRESS", nullable = false, length = 256)
    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @Column(name = "USER_TYPE", length = 20)
    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    @Column(name = "STATUS", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
