package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 29, 2015 5:33:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.sql.Clob;
import java.util.Date;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "NOTIFICATION")
public class Notification implements java.io.Serializable {

    private String id;
    private String appId;
    private String origTmplId;
    private String senderId;
    private String senderEmail;
    private Clob content;
    private String type;
    private Date sentOn;
    private Character unread;

    public Notification() {
    }

    public Notification(String id) {
        this.id = id;
    }

    public Notification(String id, String appId, String origTmplId,
                        String senderId, String senderEmail, Clob content, String type,
                        Date sentOn, Character unread) {
        this.id = id;
        this.appId = appId;
        this.origTmplId = origTmplId;
        this.senderId = senderId;
        this.senderEmail = senderEmail;
        this.content = content;
        this.type = type;
        this.sentOn = sentOn;
        this.unread = unread;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "APP_ID", length = 25)
    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Column(name = "ORIG_TMPL_ID")
    public String getOrigTmplId() {
        return this.origTmplId;
    }

    public void setOrigTmplId(String origTmplId) {
        this.origTmplId = origTmplId;
    }

    @Column(name = "SENDER_ID")
    public String getSenderId() {
        return this.senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    @Column(name = "SENDER_EMAIL")
    public String getSenderEmail() {
        return this.senderEmail;
    }

    public void setSenderEmail(String senderEmail) {
        this.senderEmail = senderEmail;
    }

    @Column(name = "CONTENT")
    public Clob getContent() {
        return this.content;
    }

    public void setContent(Clob content) {
        this.content = content;
    }

    @Column(name = "TYPE", length = 25)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "SENT_ON", length = 7)
    public Date getSentOn() {
        return this.sentOn;
    }

    public void setSentOn(Date sentOn) {
        this.sentOn = sentOn;
    }

    @Column(name = "UNREAD", length = 1)
    public Character getUnread() {
        return this.unread;
    }

    public void setUnread(Character unread) {
        this.unread = unread;
    }

}
