package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissionGroupsId generated by hbm2java
 */
@Embeddable
public class PermissionGroupsId implements java.io.Serializable {

    private String permissionCd;
    private String permissionGroupCd;

    public PermissionGroupsId() {
    }

    public PermissionGroupsId(String permissionCd, String permissionGroupCd) {
        this.permissionCd = permissionCd;
        this.permissionGroupCd = permissionGroupCd;
    }

    @Column(name = "PERMISSION_CD", nullable = false, length = 25)
    public String getPermissionCd() {
        return permissionCd;
    }

    public void setPermissionCd(String permissionCd) {
        this.permissionCd = permissionCd;
    }

    @Column(name = "PERMISSION_GROUP_CD", nullable = false, length = 25)
    public String getPermissionGroupCd() {
        return permissionGroupCd;
    }

    public void setPermissionGroupCd(String permissionGroupCd) {
        this.permissionGroupCd = permissionGroupCd;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof PermissionGroupsId)) {
            return false;
        }
        final PermissionGroupsId castOther = (PermissionGroupsId) other;

        return (getPermissionCd() == castOther.getPermissionCd() || getPermissionCd() != null
                && castOther.getPermissionCd() != null
                && getPermissionCd().equals(castOther.getPermissionCd()))
                && (getPermissionGroupCd() == castOther.getPermissionGroupCd() || getPermissionGroupCd() != null
                        && castOther.getPermissionGroupCd() != null
                        && getPermissionGroupCd().equals(
                                castOther.getPermissionGroupCd()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getPermissionCd() == null ? 0 : getPermissionCd().hashCode());
        result = 37
                * result
                + (getPermissionGroupCd() == null ? 0 : getPermissionGroupCd()
                        .hashCode());
        return result;
    }

}
