package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/**
 * RolePermissionsId generated by hbm2java
 */
@Embeddable
public class RolePermissionsId implements java.io.Serializable {

    private Integer roleId;
    private String permissionCd;
    private String roleLevelDataAccess;
    private Date createdDate;
    private Integer createdBy;
    private Date updatedDate;
    private Integer updatedBy;

    public RolePermissionsId() {
    }

    public RolePermissionsId(Integer roleId, String permissionCd,
                             String roleLevelDataAccess, Date createdDate, Integer createdBy,
                             Date updatedDate, Integer updatedBy) {
        this.roleId = roleId;
        this.permissionCd = permissionCd;
        this.roleLevelDataAccess = roleLevelDataAccess;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updatedDate = updatedDate;
        this.updatedBy = updatedBy;
    }

    @Column(name = "ROLE_ID", precision = 22, scale = 0)
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Column(name = "PERMISSION_CD", length = 25)
    public String getPermissionCd() {
        return this.permissionCd;
    }

    public void setPermissionCd(String permissionCd) {
        this.permissionCd = permissionCd;
    }

    @Column(name = "ROLE_LEVEL_DATA_ACCESS", length = 500)
    public String getRoleLevelDataAccess() {
        return this.roleLevelDataAccess;
    }

    public void setRoleLevelDataAccess(String roleLevelDataAccess) {
        this.roleLevelDataAccess = roleLevelDataAccess;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "CREATED_BY", precision = 22, scale = 0)
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Column(name = "UPDATED_BY", precision = 22, scale = 0)
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RolePermissionsId))
            return false;
        RolePermissionsId castOther = (RolePermissionsId) other;

        return ((this.getRoleId() == castOther.getRoleId()) || (this
                .getRoleId() != null && castOther.getRoleId() != null && this
                .getRoleId().equals(castOther.getRoleId())))
                && ((this.getPermissionCd() == castOther.getPermissionCd()) || (this
                .getPermissionCd() != null
                && castOther.getPermissionCd() != null && this
                .getPermissionCd().equals(castOther.getPermissionCd())))
                && ((this.getRoleLevelDataAccess() == castOther
                .getRoleLevelDataAccess()) || (this
                .getRoleLevelDataAccess() != null
                && castOther.getRoleLevelDataAccess() != null && this
                .getRoleLevelDataAccess().equals(
                        castOther.getRoleLevelDataAccess())))
                && ((this.getCreatedDate() == castOther.getCreatedDate()) || (this
                .getCreatedDate() != null
                && castOther.getCreatedDate() != null && this
                .getCreatedDate().equals(castOther.getCreatedDate())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
                .getCreatedBy() != null
                && castOther.getCreatedBy() != null && this
                .getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getUpdatedDate() == castOther.getUpdatedDate()) || (this
                .getUpdatedDate() != null
                && castOther.getUpdatedDate() != null && this
                .getUpdatedDate().equals(castOther.getUpdatedDate())))
                && ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this
                .getUpdatedBy() != null
                && castOther.getUpdatedBy() != null && this
                .getUpdatedBy().equals(castOther.getUpdatedBy())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
        result = 37
                * result
                + (getPermissionCd() == null ? 0 : this.getPermissionCd()
                .hashCode());
        result = 37
                * result
                + (getRoleLevelDataAccess() == null ? 0 : this
                .getRoleLevelDataAccess().hashCode());
        result = 37
                * result
                + (getCreatedDate() == null ? 0 : this.getCreatedDate()
                .hashCode());
        result = 37 * result
                + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37
                * result
                + (getUpdatedDate() == null ? 0 : this.getUpdatedDate()
                .hashCode());
        result = 37 * result
                + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
        return result;
    }

}
