package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 29, 2015 5:33:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ScheduleTemplate generated by hbm2java
 */
@Entity
@Table(name = "SCHEDULE_TEMPLATE")
public class ScheduleTemplate implements java.io.Serializable {

    private String scheduleId;
    private String emailTmpl;
    private String onscreenTmpl;
    private Integer delay;

    public ScheduleTemplate() {
    }

    public ScheduleTemplate(String scheduleId) {
        this.scheduleId = scheduleId;
    }

    public ScheduleTemplate(String scheduleId, String emailTmpl,
                            String onscreenTmpl, Integer delay) {
        this.scheduleId = scheduleId;
        this.emailTmpl = emailTmpl;
        this.onscreenTmpl = onscreenTmpl;
        this.delay = delay;
    }

    @Id
    @Column(name = "SCHEDULE_ID", unique = true, nullable = false)
    public String getScheduleId() {
        return this.scheduleId;
    }

    public void setScheduleId(String scheduleId) {
        this.scheduleId = scheduleId;
    }

    @Column(name = "EMAIL_TMPL")
    public String getEmailTmpl() {
        return this.emailTmpl;
    }

    public void setEmailTmpl(String emailTmpl) {
        this.emailTmpl = emailTmpl;
    }

    @Column(name = "ONSCREEN_TMPL")
    public String getOnscreenTmpl() {
        return this.onscreenTmpl;
    }

    public void setOnscreenTmpl(String onscreenTmpl) {
        this.onscreenTmpl = onscreenTmpl;
    }

    @Column(name = "DELAY", precision = 22, scale = 0)
    public Integer getDelay() {
        return this.delay;
    }

    public void setDelay(Integer delay) {
        this.delay = delay;
    }

}
