package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserPreferredJournalsId generated by hbm2java
 */
@Embeddable
public class UserPreferredJournalsId implements java.io.Serializable {

    private Integer userId;
    private int journalId;

    public UserPreferredJournalsId() {
    }

    public UserPreferredJournalsId(Integer userId, int journalId) {
        this.userId = userId;
        this.journalId = journalId;
    }

    @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "JOURNAL_ID", nullable = false, precision = 22, scale = 0)
    public int getJournalId() {
        return journalId;
    }

    public void setJournalId(int journalId) {
        this.journalId = journalId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof UserPreferredJournalsId)) {
            return false;
        }
        final UserPreferredJournalsId castOther = (UserPreferredJournalsId) other;

        return (getUserId() == castOther.getUserId() || getUserId() != null
                && castOther.getUserId() != null
                && getUserId().equals(castOther.getUserId()))
                && getJournalId() == castOther.getJournalId();
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getUserId() == null ? 0 : getUserId().hashCode());
        result = 37 * result + getJournalId();
        return result;
    }

}
