package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", uniqueConstraints = @UniqueConstraint(columnNames = "PRIMARY_EMAIL_ADDR"))
public class Users implements java.io.Serializable {

    private Integer userId;
    private Users usersByCreatedBy;
    private Users usersByUpdatedBy;
    private String firstName;
    private String lastName;
    private String primaryEmailAddr;
    private Integer as1UserId;
    private Integer invalidLoginCnt;
    private Date accountLockedTime;
    private Date lastLoginDate;
    private Date createdDate;
    private Date updatedDate;
    private Set<AuditDetails> auditDetailsesForUserId = new HashSet<AuditDetails>(
            0);
    private Set<AuthColleagueDetails> authColleagueDetailsesForCreatedBy = new HashSet<AuthColleagueDetails>(
            0);
    private Set<LockedAccountDetails> lockedAccountDetailsesForCreatedBy = new HashSet<LockedAccountDetails>(
            0);
    private Set<UserAlerts> userAlertsesForUpdatedBy = new HashSet<UserAlerts>(
            0);
    private Set<UserWoaAccounts> userWoaAccountsesForCreatedBy = new HashSet<UserWoaAccounts>(
            0);
    private Set<Journals> journalsesForUpdatedBy = new HashSet<Journals>(0);
    private Set<UserAlerts> userAlertsesForCreatedBy = new HashSet<UserAlerts>(
            0);
    private Set<Journals> journalsesForCreatedBy = new HashSet<Journals>(0);
    private Set<AuthColleagueDetails> authColleagueDetailsesForUpdatedBy = new HashSet<AuthColleagueDetails>(
            0);
    private Set<AdditionalPermissions> additionalPermissionsesForUserId = new HashSet<AdditionalPermissions>(
            0);
    private Set<AdminProfile> adminProfilesForCreatedBy = new HashSet<AdminProfile>(
            0);
    private Set<Address> addressesForUpdatedBy = new HashSet<Address>(0);
    private Set<Address> addressesForCreatedBy = new HashSet<Address>(0);
    private Set<Users> usersesForUpdatedBy = new HashSet<Users>(0);
    private Set<Users> usersesForCreatedBy = new HashSet<Users>(0);
    private Set<UserAddresses> userAddressesesForUpdatedBy = new HashSet<UserAddresses>(
            0);
    private Set<UserProfile> userProfilesForMergerAccntId = new HashSet<UserProfile>(
            0);
    private Set<UserAddresses> userAddressesesForCreatedBy = new HashSet<UserAddresses>(
            0);
    private Set<Roles> rolesesForUpdatedBy = new HashSet<Roles>(0);
    private Set<Roles> rolesesForCreatedBy = new HashSet<Roles>(0);
    private Set<UserAffiliations> userAffiliationsesForUpdatedBy = new HashSet<UserAffiliations>(
            0);
    private Set<UserAffiliations> userAffiliationsesForCreatedBy = new HashSet<UserAffiliations>(
            0);
    private Set<UserAddresses> userAddressesesForUserId = new HashSet<UserAddresses>(
            0);
    private Set<UserFunders> userFundersesForUpdatedBy = new HashSet<UserFunders>(
            0);
    private UserReferenceData userReferenceDataByUserId;
    private Set<AuthCoauthDetails> authCoauthDetailsesForCreatedBy = new HashSet<AuthCoauthDetails>(
            0);
    private Set<Alerts> alertsesForUpdatedBy = new HashSet<Alerts>(0);
    private Set<ObjectTypes> objectTypesesForUpdatedBy = new HashSet<ObjectTypes>(
            0);
    private Set<UserAreaOfInterest> userAreaOfInterestsForUpdatedBy = new HashSet<UserAreaOfInterest>(
            0);
    private Set<Alerts> alertsesForCreatedBy = new HashSet<Alerts>(0);
    private Set<ObjectTypes> objectTypesesForCreatedBy = new HashSet<ObjectTypes>(
            0);
    private Set<UserAreaOfInterest> userAreaOfInterestsForCreatedBy = new HashSet<UserAreaOfInterest>(
            0);
    private Set<Actions> actionsesForUpdatedBy = new HashSet<Actions>(0);
    private Set<AdminProfile> adminProfilesForUpdatedBy = new HashSet<AdminProfile>(
            0);
    private Set<Actions> actionsesForCreatedBy = new HashSet<Actions>(0);
    private Set<LockedAccountDetails> lockedAccountDetailsesForUpdatedBy = new HashSet<LockedAccountDetails>(
            0);
    private Set<UserWoaAccounts> userWoaAccountsesForUpdatedBy = new HashSet<UserWoaAccounts>(
            0);
    private Set<AuditDetails> auditDetailsesForCreatedBy = new HashSet<AuditDetails>(
            0);
    private Set<LookupValues> lookupValuesesForUpdatedBy = new HashSet<LookupValues>(
            0);
    private Set<LookupValues> lookupValuesesForCreatedBy = new HashSet<LookupValues>(
            0);
    private Set<UserFunders> userFundersesForCreatedBy = new HashSet<UserFunders>(
            0);
    private Set<AddressType> addressTypesForUpdatedBy = new HashSet<AddressType>(
            0);
    private Set<AreaOfInterest> areaOfInterestsForUpdatedBy = new HashSet<AreaOfInterest>(
            0);
    private Set<AddressType> addressTypesForCreatedBy = new HashSet<AddressType>(
            0);
    private Set<AreaOfInterest> areaOfInterestsForCreatedBy = new HashSet<AreaOfInterest>(
            0);
    private Set<UserFunderGrants> userFunderGrantsesForUpdatedBy = new HashSet<UserFunderGrants>(
            0);
    private Set<UserFunderGrants> userFunderGrantsesForCreatedBy = new HashSet<UserFunderGrants>(
            0);
    private Set<Societies> societiesesForUpdatedBy = new HashSet<Societies>(0);
    private Set<UserProfile> userProfilesForUpdatedBy = new HashSet<UserProfile>(
            0);
    private Set<PermissionGroups> permissionGroupsesForCreatedBy = new HashSet<PermissionGroups>(
            0);
    private Set<UserProfileAttribVisible> userProfileAttribVisiblesForCreatedBy = new HashSet<UserProfileAttribVisible>(
            0);
    private Set<Permissions> permissionsesForUpdatedBy = new HashSet<Permissions>(
            0);
    private Set<Permissions> permissionsesForCreatedBy = new HashSet<Permissions>(
            0);
    private Set<AuthCoauthDetails> authCoauthDetailsesForUpdatedBy = new HashSet<AuthCoauthDetails>(
            0);
    private Set<Societies> societiesesForCreatedBy = new HashSet<Societies>(0);
    private Set<UserProfile> userProfilesForCreatedBy = new HashSet<UserProfile>(
            0);
    private Set<ResearchFunders> researchFundersesForUpdatedBy = new HashSet<ResearchFunders>(
            0);
    private Set<ResearchFunders> researchFundersesForCreatedBy = new HashSet<ResearchFunders>(
            0);
    private AdminProfile adminProfileByUserId;
    private Set<PermissionGroups> permissionGroupsesForUpdatedBy = new HashSet<PermissionGroups>(
            0);
    private Set<UserProfileAttribVisible> userProfileAttribVisiblesForUpdatedBy = new HashSet<UserProfileAttribVisible>(
            0);
    private Set<RolePermissions> rolePermissionsesForUpdatedBy = new HashSet<RolePermissions>(
            0);
    private UserProfile userProfileByUserId;
    private Set<RolePermissions> rolePermissionsesForCreatedBy = new HashSet<RolePermissions>(
            0);
    private Set<UserRoles> userRolesesForUpdatedBy = new HashSet<UserRoles>(0);
    private Set<UserRoles> userRolesesForCreatedBy = new HashSet<UserRoles>(0);
    private Set<UserReferenceData> userReferenceDatasForUpdatedBy = new HashSet<UserReferenceData>(
            0);
    private Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForUpdatedBy = new HashSet<UserSecondaryEmailAddr>(
            0);
    private Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForCreatedBy = new HashSet<UserSecondaryEmailAddr>(
            0);
    private Set<ProfileAttributeList> profileAttributeListsForCreatedBy = new HashSet<ProfileAttributeList>(
            0);
    private Set<UserPreferredJournals> userPreferredJournalsesForUpdatedBy = new HashSet<UserPreferredJournals>(
            0);
    private Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForUserId = new HashSet<UserSecondaryEmailAddr>(
            0);
    private Set<UserPreferredJournals> userPreferredJournalsesForCreatedBy = new HashSet<UserPreferredJournals>(
            0);
    private Set<UserSocietyDetails> userSocietyDetailsesForUpdatedBy = new HashSet<UserSocietyDetails>(
            0);
    private Set<UserSocietyDetails> userSocietyDetailsesForCreatedBy = new HashSet<UserSocietyDetails>(
            0);
    private Set<UserReferenceData> userReferenceDatasForCreatedBy = new HashSet<UserReferenceData>(
            0);
    private Set<UserRoles> userRolesesForUserId = new HashSet<UserRoles>(0);
    private Set<AdditionalPermissions> additionalPermissionsesForUpdatedBy = new HashSet<AdditionalPermissions>(
            0);
    private Set<AdditionalPermissions> additionalPermissionsesForCreatedBy = new HashSet<AdditionalPermissions>(
            0);
    private Set<ProfileAttributeList> profileAttributeListsForUpdatedBy = new HashSet<ProfileAttributeList>(
            0);

    public Users() {
    }

    public Users(Integer userId, String primaryEmailAddr) {
        this.userId = userId;
        this.primaryEmailAddr = primaryEmailAddr;
    }

    public Users(
            Integer userId,
            Users usersByCreatedBy,
            Users usersByUpdatedBy,
            String firstName,
            String lastName,
            String primaryEmailAddr,
            Integer as1UserId,
            Integer invalidLoginCnt,
            Date accountLockedTime,
            Date lastLoginDate,
            Date createdDate,
            Date updatedDate,
            Set<AuditDetails> auditDetailsesForUserId,
            Set<AuthColleagueDetails> authColleagueDetailsesForCreatedBy,
            Set<LockedAccountDetails> lockedAccountDetailsesForCreatedBy,
            Set<UserAlerts> userAlertsesForUpdatedBy,
            Set<UserWoaAccounts> userWoaAccountsesForCreatedBy,
            Set<Journals> journalsesForUpdatedBy,
            Set<UserAlerts> userAlertsesForCreatedBy,
            Set<Journals> journalsesForCreatedBy,
            Set<AuthColleagueDetails> authColleagueDetailsesForUpdatedBy,
            Set<AdditionalPermissions> additionalPermissionsesForUserId,
            Set<AdminProfile> adminProfilesForCreatedBy,
            Set<Address> addressesForUpdatedBy,
            Set<Address> addressesForCreatedBy,
            Set<Users> usersesForUpdatedBy,
            Set<Users> usersesForCreatedBy,
            Set<UserAddresses> userAddressesesForUpdatedBy,
            Set<UserProfile> userProfilesForMergerAccntId,
            Set<UserAddresses> userAddressesesForCreatedBy,
            Set<Roles> rolesesForUpdatedBy,
            Set<Roles> rolesesForCreatedBy,
            Set<UserAffiliations> userAffiliationsesForUpdatedBy,
            Set<UserAffiliations> userAffiliationsesForCreatedBy,
            Set<UserAddresses> userAddressesesForUserId,
            Set<UserFunders> userFundersesForUpdatedBy,
            UserReferenceData userReferenceDataByUserId,
            Set<AuthCoauthDetails> authCoauthDetailsesForCreatedBy,
            Set<Alerts> alertsesForUpdatedBy,
            Set<ObjectTypes> objectTypesesForUpdatedBy,
            Set<UserAreaOfInterest> userAreaOfInterestsForUpdatedBy,
            Set<Alerts> alertsesForCreatedBy,
            Set<ObjectTypes> objectTypesesForCreatedBy,
            Set<UserAreaOfInterest> userAreaOfInterestsForCreatedBy,
            Set<Actions> actionsesForUpdatedBy,
            Set<AdminProfile> adminProfilesForUpdatedBy,
            Set<Actions> actionsesForCreatedBy,
            Set<LockedAccountDetails> lockedAccountDetailsesForUpdatedBy,
            Set<UserWoaAccounts> userWoaAccountsesForUpdatedBy,
            Set<AuditDetails> auditDetailsesForCreatedBy,
            Set<LookupValues> lookupValuesesForUpdatedBy,
            Set<LookupValues> lookupValuesesForCreatedBy,
            Set<UserFunders> userFundersesForCreatedBy,
            Set<AddressType> addressTypesForUpdatedBy,
            Set<AreaOfInterest> areaOfInterestsForUpdatedBy,
            Set<AddressType> addressTypesForCreatedBy,
            Set<AreaOfInterest> areaOfInterestsForCreatedBy,
            Set<UserFunderGrants> userFunderGrantsesForUpdatedBy,
            Set<UserFunderGrants> userFunderGrantsesForCreatedBy,
            Set<Societies> societiesesForUpdatedBy,
            Set<UserProfile> userProfilesForUpdatedBy,
            Set<PermissionGroups> permissionGroupsesForCreatedBy,
            Set<UserProfileAttribVisible> userProfileAttribVisiblesForCreatedBy,
            Set<Permissions> permissionsesForUpdatedBy,
            Set<Permissions> permissionsesForCreatedBy,
            Set<AuthCoauthDetails> authCoauthDetailsesForUpdatedBy,
            Set<Societies> societiesesForCreatedBy,
            Set<UserProfile> userProfilesForCreatedBy,
            Set<ResearchFunders> researchFundersesForUpdatedBy,
            Set<ResearchFunders> researchFundersesForCreatedBy,
            AdminProfile adminProfileByUserId,
            Set<PermissionGroups> permissionGroupsesForUpdatedBy,
            Set<UserProfileAttribVisible> userProfileAttribVisiblesForUpdatedBy,
            Set<RolePermissions> rolePermissionsesForUpdatedBy,
            UserProfile userProfileByUserId,
            Set<RolePermissions> rolePermissionsesForCreatedBy,
            Set<UserRoles> userRolesesForUpdatedBy,
            Set<UserRoles> userRolesesForCreatedBy,
            Set<UserReferenceData> userReferenceDatasForUpdatedBy,
            Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForUpdatedBy,
            Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForCreatedBy,
            Set<ProfileAttributeList> profileAttributeListsForCreatedBy,
            Set<UserPreferredJournals> userPreferredJournalsesForUpdatedBy,
            Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForUserId,
            Set<UserPreferredJournals> userPreferredJournalsesForCreatedBy,
            Set<UserSocietyDetails> userSocietyDetailsesForUpdatedBy,
            Set<UserSocietyDetails> userSocietyDetailsesForCreatedBy,
            Set<UserReferenceData> userReferenceDatasForCreatedBy,
            Set<UserRoles> userRolesesForUserId,
            Set<AdditionalPermissions> additionalPermissionsesForUpdatedBy,
            Set<AdditionalPermissions> additionalPermissionsesForCreatedBy,
            Set<ProfileAttributeList> profileAttributeListsForUpdatedBy) {
        this.userId = userId;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByUpdatedBy = usersByUpdatedBy;
        this.firstName = firstName;
        this.lastName = lastName;
        this.primaryEmailAddr = primaryEmailAddr;
        this.as1UserId = as1UserId;
        this.invalidLoginCnt = invalidLoginCnt;
        this.accountLockedTime = accountLockedTime;
        this.lastLoginDate = lastLoginDate;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.auditDetailsesForUserId = auditDetailsesForUserId;
        this.authColleagueDetailsesForCreatedBy = authColleagueDetailsesForCreatedBy;
        this.lockedAccountDetailsesForCreatedBy = lockedAccountDetailsesForCreatedBy;
        this.userAlertsesForUpdatedBy = userAlertsesForUpdatedBy;
        this.userWoaAccountsesForCreatedBy = userWoaAccountsesForCreatedBy;
        this.journalsesForUpdatedBy = journalsesForUpdatedBy;
        this.userAlertsesForCreatedBy = userAlertsesForCreatedBy;
        this.journalsesForCreatedBy = journalsesForCreatedBy;
        this.authColleagueDetailsesForUpdatedBy = authColleagueDetailsesForUpdatedBy;
        this.additionalPermissionsesForUserId = additionalPermissionsesForUserId;
        this.adminProfilesForCreatedBy = adminProfilesForCreatedBy;
        this.addressesForUpdatedBy = addressesForUpdatedBy;
        this.addressesForCreatedBy = addressesForCreatedBy;
        this.usersesForUpdatedBy = usersesForUpdatedBy;
        this.usersesForCreatedBy = usersesForCreatedBy;
        this.userAddressesesForUpdatedBy = userAddressesesForUpdatedBy;
        this.userProfilesForMergerAccntId = userProfilesForMergerAccntId;
        this.userAddressesesForCreatedBy = userAddressesesForCreatedBy;
        this.rolesesForUpdatedBy = rolesesForUpdatedBy;
        this.rolesesForCreatedBy = rolesesForCreatedBy;
        this.userAffiliationsesForUpdatedBy = userAffiliationsesForUpdatedBy;
        this.userAffiliationsesForCreatedBy = userAffiliationsesForCreatedBy;
        this.userAddressesesForUserId = userAddressesesForUserId;
        this.userFundersesForUpdatedBy = userFundersesForUpdatedBy;
        this.userReferenceDataByUserId = userReferenceDataByUserId;
        this.authCoauthDetailsesForCreatedBy = authCoauthDetailsesForCreatedBy;
        this.alertsesForUpdatedBy = alertsesForUpdatedBy;
        this.objectTypesesForUpdatedBy = objectTypesesForUpdatedBy;
        this.userAreaOfInterestsForUpdatedBy = userAreaOfInterestsForUpdatedBy;
        this.alertsesForCreatedBy = alertsesForCreatedBy;
        this.objectTypesesForCreatedBy = objectTypesesForCreatedBy;
        this.userAreaOfInterestsForCreatedBy = userAreaOfInterestsForCreatedBy;
        this.actionsesForUpdatedBy = actionsesForUpdatedBy;
        this.adminProfilesForUpdatedBy = adminProfilesForUpdatedBy;
        this.actionsesForCreatedBy = actionsesForCreatedBy;
        this.lockedAccountDetailsesForUpdatedBy = lockedAccountDetailsesForUpdatedBy;
        this.userWoaAccountsesForUpdatedBy = userWoaAccountsesForUpdatedBy;
        this.auditDetailsesForCreatedBy = auditDetailsesForCreatedBy;
        this.lookupValuesesForUpdatedBy = lookupValuesesForUpdatedBy;
        this.lookupValuesesForCreatedBy = lookupValuesesForCreatedBy;
        this.userFundersesForCreatedBy = userFundersesForCreatedBy;
        this.addressTypesForUpdatedBy = addressTypesForUpdatedBy;
        this.areaOfInterestsForUpdatedBy = areaOfInterestsForUpdatedBy;
        this.addressTypesForCreatedBy = addressTypesForCreatedBy;
        this.areaOfInterestsForCreatedBy = areaOfInterestsForCreatedBy;
        this.userFunderGrantsesForUpdatedBy = userFunderGrantsesForUpdatedBy;
        this.userFunderGrantsesForCreatedBy = userFunderGrantsesForCreatedBy;
        this.societiesesForUpdatedBy = societiesesForUpdatedBy;
        this.userProfilesForUpdatedBy = userProfilesForUpdatedBy;
        this.permissionGroupsesForCreatedBy = permissionGroupsesForCreatedBy;
        this.userProfileAttribVisiblesForCreatedBy = userProfileAttribVisiblesForCreatedBy;
        this.permissionsesForUpdatedBy = permissionsesForUpdatedBy;
        this.permissionsesForCreatedBy = permissionsesForCreatedBy;
        this.authCoauthDetailsesForUpdatedBy = authCoauthDetailsesForUpdatedBy;
        this.societiesesForCreatedBy = societiesesForCreatedBy;
        this.userProfilesForCreatedBy = userProfilesForCreatedBy;
        this.researchFundersesForUpdatedBy = researchFundersesForUpdatedBy;
        this.researchFundersesForCreatedBy = researchFundersesForCreatedBy;
        this.adminProfileByUserId = adminProfileByUserId;
        this.permissionGroupsesForUpdatedBy = permissionGroupsesForUpdatedBy;
        this.userProfileAttribVisiblesForUpdatedBy = userProfileAttribVisiblesForUpdatedBy;
        this.rolePermissionsesForUpdatedBy = rolePermissionsesForUpdatedBy;
        this.userProfileByUserId = userProfileByUserId;
        this.rolePermissionsesForCreatedBy = rolePermissionsesForCreatedBy;
        this.userRolesesForUpdatedBy = userRolesesForUpdatedBy;
        this.userRolesesForCreatedBy = userRolesesForCreatedBy;
        this.userReferenceDatasForUpdatedBy = userReferenceDatasForUpdatedBy;
        this.userSecondaryEmailAddrsForUpdatedBy = userSecondaryEmailAddrsForUpdatedBy;
        this.userSecondaryEmailAddrsForCreatedBy = userSecondaryEmailAddrsForCreatedBy;
        this.profileAttributeListsForCreatedBy = profileAttributeListsForCreatedBy;
        this.userPreferredJournalsesForUpdatedBy = userPreferredJournalsesForUpdatedBy;
        this.userSecondaryEmailAddrsForUserId = userSecondaryEmailAddrsForUserId;
        this.userPreferredJournalsesForCreatedBy = userPreferredJournalsesForCreatedBy;
        this.userSocietyDetailsesForUpdatedBy = userSocietyDetailsesForUpdatedBy;
        this.userSocietyDetailsesForCreatedBy = userSocietyDetailsesForCreatedBy;
        this.userReferenceDatasForCreatedBy = userReferenceDatasForCreatedBy;
        this.userRolesesForUserId = userRolesesForUserId;
        this.additionalPermissionsesForUpdatedBy = additionalPermissionsesForUpdatedBy;
        this.additionalPermissionsesForCreatedBy = additionalPermissionsesForCreatedBy;
        this.profileAttributeListsForUpdatedBy = profileAttributeListsForUpdatedBy;
    }

    @Id
    @Column(name = "USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "USER_SEQ")
    @SequenceGenerator(name = "USER_SEQ", sequenceName = "USER_SEQ", allocationSize = 1)
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY")
    public Users getUsersByCreatedBy() {
        return usersByCreatedBy;
    }

    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPDATED_BY")
    public Users getUsersByUpdatedBy() {
        return usersByUpdatedBy;
    }

    public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
        this.usersByUpdatedBy = usersByUpdatedBy;
    }

    @Column(name = "FIRST_NAME", length = 100)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "LAST_NAME", length = 100)
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "PRIMARY_EMAIL_ADDR", unique = true, nullable = false, length = 100)
    public String getPrimaryEmailAddr() {
        return primaryEmailAddr;
    }

    public void setPrimaryEmailAddr(String primaryEmailAddr) {
        this.primaryEmailAddr = primaryEmailAddr;
    }

    @Column(name = "AS1_USER_ID", precision = 22, scale = 0)
    public Integer getAs1UserId() {
        return as1UserId;
    }

    public void setAs1UserId(Integer as1UserId) {
        this.as1UserId = as1UserId;
    }

    @Column(name = "INVALID_LOGIN_CNT", precision = 2, scale = 0)
    public Integer getInvalidLoginCnt() {
        return invalidLoginCnt;
    }

    public void setInvalidLoginCnt(Integer invalidLoginCnt) {
        this.invalidLoginCnt = invalidLoginCnt;
    }

    @Column(name = "ACCOUNT_LOCKED_TIME")
    public Date getAccountLockedTime() {
        return accountLockedTime;
    }

    public void setAccountLockedTime(Date accountLockedTime) {
        this.accountLockedTime = accountLockedTime;
    }

    @Column(name = "LAST_LOGIN_DATE")
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public Set<AuditDetails> getAuditDetailsesForUserId() {
        return auditDetailsesForUserId;
    }

    public void setAuditDetailsesForUserId(
            Set<AuditDetails> auditDetailsesForUserId) {
        this.auditDetailsesForUserId = auditDetailsesForUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AuthColleagueDetails> getAuthColleagueDetailsesForCreatedBy() {
        return authColleagueDetailsesForCreatedBy;
    }

    public void setAuthColleagueDetailsesForCreatedBy(
            Set<AuthColleagueDetails> authColleagueDetailsesForCreatedBy) {
        this.authColleagueDetailsesForCreatedBy = authColleagueDetailsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<LockedAccountDetails> getLockedAccountDetailsesForCreatedBy() {
        return lockedAccountDetailsesForCreatedBy;
    }

    public void setLockedAccountDetailsesForCreatedBy(
            Set<LockedAccountDetails> lockedAccountDetailsesForCreatedBy) {
        this.lockedAccountDetailsesForCreatedBy = lockedAccountDetailsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserAlerts> getUserAlertsesForUpdatedBy() {
        return userAlertsesForUpdatedBy;
    }

    public void setUserAlertsesForUpdatedBy(
            Set<UserAlerts> userAlertsesForUpdatedBy) {
        this.userAlertsesForUpdatedBy = userAlertsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserWoaAccounts> getUserWoaAccountsesForCreatedBy() {
        return userWoaAccountsesForCreatedBy;
    }

    public void setUserWoaAccountsesForCreatedBy(
            Set<UserWoaAccounts> userWoaAccountsesForCreatedBy) {
        this.userWoaAccountsesForCreatedBy = userWoaAccountsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Journals> getJournalsesForUpdatedBy() {
        return journalsesForUpdatedBy;
    }

    public void setJournalsesForUpdatedBy(Set<Journals> journalsesForUpdatedBy) {
        this.journalsesForUpdatedBy = journalsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserAlerts> getUserAlertsesForCreatedBy() {
        return userAlertsesForCreatedBy;
    }

    public void setUserAlertsesForCreatedBy(
            Set<UserAlerts> userAlertsesForCreatedBy) {
        this.userAlertsesForCreatedBy = userAlertsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Journals> getJournalsesForCreatedBy() {
        return journalsesForCreatedBy;
    }

    public void setJournalsesForCreatedBy(Set<Journals> journalsesForCreatedBy) {
        this.journalsesForCreatedBy = journalsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<AuthColleagueDetails> getAuthColleagueDetailsesForUpdatedBy() {
        return authColleagueDetailsesForUpdatedBy;
    }

    public void setAuthColleagueDetailsesForUpdatedBy(
            Set<AuthColleagueDetails> authColleagueDetailsesForUpdatedBy) {
        this.authColleagueDetailsesForUpdatedBy = authColleagueDetailsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public Set<AdditionalPermissions> getAdditionalPermissionsesForUserId() {
        return additionalPermissionsesForUserId;
    }

    public void setAdditionalPermissionsesForUserId(
            Set<AdditionalPermissions> additionalPermissionsesForUserId) {
        this.additionalPermissionsesForUserId = additionalPermissionsesForUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AdminProfile> getAdminProfilesForCreatedBy() {
        return adminProfilesForCreatedBy;
    }

    public void setAdminProfilesForCreatedBy(
            Set<AdminProfile> adminProfilesForCreatedBy) {
        this.adminProfilesForCreatedBy = adminProfilesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Address> getAddressesForUpdatedBy() {
        return addressesForUpdatedBy;
    }

    public void setAddressesForUpdatedBy(Set<Address> addressesForUpdatedBy) {
        this.addressesForUpdatedBy = addressesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Address> getAddressesForCreatedBy() {
        return addressesForCreatedBy;
    }

    public void setAddressesForCreatedBy(Set<Address> addressesForCreatedBy) {
        this.addressesForCreatedBy = addressesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Users> getUsersesForUpdatedBy() {
        return usersesForUpdatedBy;
    }

    public void setUsersesForUpdatedBy(Set<Users> usersesForUpdatedBy) {
        this.usersesForUpdatedBy = usersesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Users> getUsersesForCreatedBy() {
        return usersesForCreatedBy;
    }

    public void setUsersesForCreatedBy(Set<Users> usersesForCreatedBy) {
        this.usersesForCreatedBy = usersesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserAddresses> getUserAddressesesForUpdatedBy() {
        return userAddressesesForUpdatedBy;
    }

    public void setUserAddressesesForUpdatedBy(
            Set<UserAddresses> userAddressesesForUpdatedBy) {
        this.userAddressesesForUpdatedBy = userAddressesesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByMergerAccntId")
    public Set<UserProfile> getUserProfilesForMergerAccntId() {
        return userProfilesForMergerAccntId;
    }

    public void setUserProfilesForMergerAccntId(
            Set<UserProfile> userProfilesForMergerAccntId) {
        this.userProfilesForMergerAccntId = userProfilesForMergerAccntId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserAddresses> getUserAddressesesForCreatedBy() {
        return userAddressesesForCreatedBy;
    }

    public void setUserAddressesesForCreatedBy(
            Set<UserAddresses> userAddressesesForCreatedBy) {
        this.userAddressesesForCreatedBy = userAddressesesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Roles> getRolesesForUpdatedBy() {
        return rolesesForUpdatedBy;
    }

    public void setRolesesForUpdatedBy(Set<Roles> rolesesForUpdatedBy) {
        this.rolesesForUpdatedBy = rolesesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Roles> getRolesesForCreatedBy() {
        return rolesesForCreatedBy;
    }

    public void setRolesesForCreatedBy(Set<Roles> rolesesForCreatedBy) {
        this.rolesesForCreatedBy = rolesesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserAffiliations> getUserAffiliationsesForUpdatedBy() {
        return userAffiliationsesForUpdatedBy;
    }

    public void setUserAffiliationsesForUpdatedBy(
            Set<UserAffiliations> userAffiliationsesForUpdatedBy) {
        this.userAffiliationsesForUpdatedBy = userAffiliationsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserAffiliations> getUserAffiliationsesForCreatedBy() {
        return userAffiliationsesForCreatedBy;
    }

    public void setUserAffiliationsesForCreatedBy(
            Set<UserAffiliations> userAffiliationsesForCreatedBy) {
        this.userAffiliationsesForCreatedBy = userAffiliationsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public Set<UserAddresses> getUserAddressesesForUserId() {
        return userAddressesesForUserId;
    }

    public void setUserAddressesesForUserId(
            Set<UserAddresses> userAddressesesForUserId) {
        this.userAddressesesForUserId = userAddressesesForUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserFunders> getUserFundersesForUpdatedBy() {
        return userFundersesForUpdatedBy;
    }

    public void setUserFundersesForUpdatedBy(
            Set<UserFunders> userFundersesForUpdatedBy) {
        this.userFundersesForUpdatedBy = userFundersesForUpdatedBy;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public UserReferenceData getUserReferenceDataByUserId() {
        return userReferenceDataByUserId;
    }

    public void setUserReferenceDataByUserId(
            UserReferenceData userReferenceDataByUserId) {
        this.userReferenceDataByUserId = userReferenceDataByUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AuthCoauthDetails> getAuthCoauthDetailsesForCreatedBy() {
        return authCoauthDetailsesForCreatedBy;
    }

    public void setAuthCoauthDetailsesForCreatedBy(
            Set<AuthCoauthDetails> authCoauthDetailsesForCreatedBy) {
        this.authCoauthDetailsesForCreatedBy = authCoauthDetailsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Alerts> getAlertsesForUpdatedBy() {
        return alertsesForUpdatedBy;
    }

    public void setAlertsesForUpdatedBy(Set<Alerts> alertsesForUpdatedBy) {
        this.alertsesForUpdatedBy = alertsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<ObjectTypes> getObjectTypesesForUpdatedBy() {
        return objectTypesesForUpdatedBy;
    }

    public void setObjectTypesesForUpdatedBy(
            Set<ObjectTypes> objectTypesesForUpdatedBy) {
        this.objectTypesesForUpdatedBy = objectTypesesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserAreaOfInterest> getUserAreaOfInterestsForUpdatedBy() {
        return userAreaOfInterestsForUpdatedBy;
    }

    public void setUserAreaOfInterestsForUpdatedBy(
            Set<UserAreaOfInterest> userAreaOfInterestsForUpdatedBy) {
        this.userAreaOfInterestsForUpdatedBy = userAreaOfInterestsForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Alerts> getAlertsesForCreatedBy() {
        return alertsesForCreatedBy;
    }

    public void setAlertsesForCreatedBy(Set<Alerts> alertsesForCreatedBy) {
        this.alertsesForCreatedBy = alertsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<ObjectTypes> getObjectTypesesForCreatedBy() {
        return objectTypesesForCreatedBy;
    }

    public void setObjectTypesesForCreatedBy(
            Set<ObjectTypes> objectTypesesForCreatedBy) {
        this.objectTypesesForCreatedBy = objectTypesesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserAreaOfInterest> getUserAreaOfInterestsForCreatedBy() {
        return userAreaOfInterestsForCreatedBy;
    }

    public void setUserAreaOfInterestsForCreatedBy(
            Set<UserAreaOfInterest> userAreaOfInterestsForCreatedBy) {
        this.userAreaOfInterestsForCreatedBy = userAreaOfInterestsForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Actions> getActionsesForUpdatedBy() {
        return actionsesForUpdatedBy;
    }

    public void setActionsesForUpdatedBy(Set<Actions> actionsesForUpdatedBy) {
        this.actionsesForUpdatedBy = actionsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<AdminProfile> getAdminProfilesForUpdatedBy() {
        return adminProfilesForUpdatedBy;
    }

    public void setAdminProfilesForUpdatedBy(
            Set<AdminProfile> adminProfilesForUpdatedBy) {
        this.adminProfilesForUpdatedBy = adminProfilesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Actions> getActionsesForCreatedBy() {
        return actionsesForCreatedBy;
    }

    public void setActionsesForCreatedBy(Set<Actions> actionsesForCreatedBy) {
        this.actionsesForCreatedBy = actionsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<LockedAccountDetails> getLockedAccountDetailsesForUpdatedBy() {
        return lockedAccountDetailsesForUpdatedBy;
    }

    public void setLockedAccountDetailsesForUpdatedBy(
            Set<LockedAccountDetails> lockedAccountDetailsesForUpdatedBy) {
        this.lockedAccountDetailsesForUpdatedBy = lockedAccountDetailsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserWoaAccounts> getUserWoaAccountsesForUpdatedBy() {
        return userWoaAccountsesForUpdatedBy;
    }

    public void setUserWoaAccountsesForUpdatedBy(
            Set<UserWoaAccounts> userWoaAccountsesForUpdatedBy) {
        this.userWoaAccountsesForUpdatedBy = userWoaAccountsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AuditDetails> getAuditDetailsesForCreatedBy() {
        return auditDetailsesForCreatedBy;
    }

    public void setAuditDetailsesForCreatedBy(
            Set<AuditDetails> auditDetailsesForCreatedBy) {
        this.auditDetailsesForCreatedBy = auditDetailsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<LookupValues> getLookupValuesesForUpdatedBy() {
        return lookupValuesesForUpdatedBy;
    }

    public void setLookupValuesesForUpdatedBy(
            Set<LookupValues> lookupValuesesForUpdatedBy) {
        this.lookupValuesesForUpdatedBy = lookupValuesesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<LookupValues> getLookupValuesesForCreatedBy() {
        return lookupValuesesForCreatedBy;
    }

    public void setLookupValuesesForCreatedBy(
            Set<LookupValues> lookupValuesesForCreatedBy) {
        this.lookupValuesesForCreatedBy = lookupValuesesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserFunders> getUserFundersesForCreatedBy() {
        return userFundersesForCreatedBy;
    }

    public void setUserFundersesForCreatedBy(
            Set<UserFunders> userFundersesForCreatedBy) {
        this.userFundersesForCreatedBy = userFundersesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<AddressType> getAddressTypesForUpdatedBy() {
        return addressTypesForUpdatedBy;
    }

    public void setAddressTypesForUpdatedBy(
            Set<AddressType> addressTypesForUpdatedBy) {
        this.addressTypesForUpdatedBy = addressTypesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<AreaOfInterest> getAreaOfInterestsForUpdatedBy() {
        return areaOfInterestsForUpdatedBy;
    }

    public void setAreaOfInterestsForUpdatedBy(
            Set<AreaOfInterest> areaOfInterestsForUpdatedBy) {
        this.areaOfInterestsForUpdatedBy = areaOfInterestsForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AddressType> getAddressTypesForCreatedBy() {
        return addressTypesForCreatedBy;
    }

    public void setAddressTypesForCreatedBy(
            Set<AddressType> addressTypesForCreatedBy) {
        this.addressTypesForCreatedBy = addressTypesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AreaOfInterest> getAreaOfInterestsForCreatedBy() {
        return areaOfInterestsForCreatedBy;
    }

    public void setAreaOfInterestsForCreatedBy(
            Set<AreaOfInterest> areaOfInterestsForCreatedBy) {
        this.areaOfInterestsForCreatedBy = areaOfInterestsForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserFunderGrants> getUserFunderGrantsesForUpdatedBy() {
        return userFunderGrantsesForUpdatedBy;
    }

    public void setUserFunderGrantsesForUpdatedBy(
            Set<UserFunderGrants> userFunderGrantsesForUpdatedBy) {
        this.userFunderGrantsesForUpdatedBy = userFunderGrantsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserFunderGrants> getUserFunderGrantsesForCreatedBy() {
        return userFunderGrantsesForCreatedBy;
    }

    public void setUserFunderGrantsesForCreatedBy(
            Set<UserFunderGrants> userFunderGrantsesForCreatedBy) {
        this.userFunderGrantsesForCreatedBy = userFunderGrantsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Societies> getSocietiesesForUpdatedBy() {
        return societiesesForUpdatedBy;
    }

    public void setSocietiesesForUpdatedBy(
            Set<Societies> societiesesForUpdatedBy) {
        this.societiesesForUpdatedBy = societiesesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserProfile> getUserProfilesForUpdatedBy() {
        return userProfilesForUpdatedBy;
    }

    public void setUserProfilesForUpdatedBy(
            Set<UserProfile> userProfilesForUpdatedBy) {
        this.userProfilesForUpdatedBy = userProfilesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<PermissionGroups> getPermissionGroupsesForCreatedBy() {
        return permissionGroupsesForCreatedBy;
    }

    public void setPermissionGroupsesForCreatedBy(
            Set<PermissionGroups> permissionGroupsesForCreatedBy) {
        this.permissionGroupsesForCreatedBy = permissionGroupsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserProfileAttribVisible> getUserProfileAttribVisiblesForCreatedBy() {
        return userProfileAttribVisiblesForCreatedBy;
    }

    public void setUserProfileAttribVisiblesForCreatedBy(
            Set<UserProfileAttribVisible> userProfileAttribVisiblesForCreatedBy) {
        this.userProfileAttribVisiblesForCreatedBy = userProfileAttribVisiblesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<Permissions> getPermissionsesForUpdatedBy() {
        return permissionsesForUpdatedBy;
    }

    public void setPermissionsesForUpdatedBy(
            Set<Permissions> permissionsesForUpdatedBy) {
        this.permissionsesForUpdatedBy = permissionsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Permissions> getPermissionsesForCreatedBy() {
        return permissionsesForCreatedBy;
    }

    public void setPermissionsesForCreatedBy(
            Set<Permissions> permissionsesForCreatedBy) {
        this.permissionsesForCreatedBy = permissionsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<AuthCoauthDetails> getAuthCoauthDetailsesForUpdatedBy() {
        return authCoauthDetailsesForUpdatedBy;
    }

    public void setAuthCoauthDetailsesForUpdatedBy(
            Set<AuthCoauthDetails> authCoauthDetailsesForUpdatedBy) {
        this.authCoauthDetailsesForUpdatedBy = authCoauthDetailsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<Societies> getSocietiesesForCreatedBy() {
        return societiesesForCreatedBy;
    }

    public void setSocietiesesForCreatedBy(
            Set<Societies> societiesesForCreatedBy) {
        this.societiesesForCreatedBy = societiesesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserProfile> getUserProfilesForCreatedBy() {
        return userProfilesForCreatedBy;
    }

    public void setUserProfilesForCreatedBy(
            Set<UserProfile> userProfilesForCreatedBy) {
        this.userProfilesForCreatedBy = userProfilesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<ResearchFunders> getResearchFundersesForUpdatedBy() {
        return researchFundersesForUpdatedBy;
    }

    public void setResearchFundersesForUpdatedBy(
            Set<ResearchFunders> researchFundersesForUpdatedBy) {
        this.researchFundersesForUpdatedBy = researchFundersesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<ResearchFunders> getResearchFundersesForCreatedBy() {
        return researchFundersesForCreatedBy;
    }

    public void setResearchFundersesForCreatedBy(
            Set<ResearchFunders> researchFundersesForCreatedBy) {
        this.researchFundersesForCreatedBy = researchFundersesForCreatedBy;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public AdminProfile getAdminProfileByUserId() {
        return adminProfileByUserId;
    }

    public void setAdminProfileByUserId(AdminProfile adminProfileByUserId) {
        this.adminProfileByUserId = adminProfileByUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<PermissionGroups> getPermissionGroupsesForUpdatedBy() {
        return permissionGroupsesForUpdatedBy;
    }

    public void setPermissionGroupsesForUpdatedBy(
            Set<PermissionGroups> permissionGroupsesForUpdatedBy) {
        this.permissionGroupsesForUpdatedBy = permissionGroupsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserProfileAttribVisible> getUserProfileAttribVisiblesForUpdatedBy() {
        return userProfileAttribVisiblesForUpdatedBy;
    }

    public void setUserProfileAttribVisiblesForUpdatedBy(
            Set<UserProfileAttribVisible> userProfileAttribVisiblesForUpdatedBy) {
        this.userProfileAttribVisiblesForUpdatedBy = userProfileAttribVisiblesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<RolePermissions> getRolePermissionsesForUpdatedBy() {
        return rolePermissionsesForUpdatedBy;
    }

    public void setRolePermissionsesForUpdatedBy(
            Set<RolePermissions> rolePermissionsesForUpdatedBy) {
        this.rolePermissionsesForUpdatedBy = rolePermissionsesForUpdatedBy;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public UserProfile getUserProfileByUserId() {
        return userProfileByUserId;
    }

    public void setUserProfileByUserId(UserProfile userProfileByUserId) {
        this.userProfileByUserId = userProfileByUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<RolePermissions> getRolePermissionsesForCreatedBy() {
        return rolePermissionsesForCreatedBy;
    }

    public void setRolePermissionsesForCreatedBy(
            Set<RolePermissions> rolePermissionsesForCreatedBy) {
        this.rolePermissionsesForCreatedBy = rolePermissionsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserRoles> getUserRolesesForUpdatedBy() {
        return userRolesesForUpdatedBy;
    }

    public void setUserRolesesForUpdatedBy(
            Set<UserRoles> userRolesesForUpdatedBy) {
        this.userRolesesForUpdatedBy = userRolesesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserRoles> getUserRolesesForCreatedBy() {
        return userRolesesForCreatedBy;
    }

    public void setUserRolesesForCreatedBy(
            Set<UserRoles> userRolesesForCreatedBy) {
        this.userRolesesForCreatedBy = userRolesesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserReferenceData> getUserReferenceDatasForUpdatedBy() {
        return userReferenceDatasForUpdatedBy;
    }

    public void setUserReferenceDatasForUpdatedBy(
            Set<UserReferenceData> userReferenceDatasForUpdatedBy) {
        this.userReferenceDatasForUpdatedBy = userReferenceDatasForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserSecondaryEmailAddr> getUserSecondaryEmailAddrsForUpdatedBy() {
        return userSecondaryEmailAddrsForUpdatedBy;
    }

    public void setUserSecondaryEmailAddrsForUpdatedBy(
            Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForUpdatedBy) {
        this.userSecondaryEmailAddrsForUpdatedBy = userSecondaryEmailAddrsForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserSecondaryEmailAddr> getUserSecondaryEmailAddrsForCreatedBy() {
        return userSecondaryEmailAddrsForCreatedBy;
    }

    public void setUserSecondaryEmailAddrsForCreatedBy(
            Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForCreatedBy) {
        this.userSecondaryEmailAddrsForCreatedBy = userSecondaryEmailAddrsForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<ProfileAttributeList> getProfileAttributeListsForCreatedBy() {
        return profileAttributeListsForCreatedBy;
    }

    public void setProfileAttributeListsForCreatedBy(
            Set<ProfileAttributeList> profileAttributeListsForCreatedBy) {
        this.profileAttributeListsForCreatedBy = profileAttributeListsForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserPreferredJournals> getUserPreferredJournalsesForUpdatedBy() {
        return userPreferredJournalsesForUpdatedBy;
    }

    public void setUserPreferredJournalsesForUpdatedBy(
            Set<UserPreferredJournals> userPreferredJournalsesForUpdatedBy) {
        this.userPreferredJournalsesForUpdatedBy = userPreferredJournalsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public Set<UserSecondaryEmailAddr> getUserSecondaryEmailAddrsForUserId() {
        return userSecondaryEmailAddrsForUserId;
    }

    public void setUserSecondaryEmailAddrsForUserId(
            Set<UserSecondaryEmailAddr> userSecondaryEmailAddrsForUserId) {
        this.userSecondaryEmailAddrsForUserId = userSecondaryEmailAddrsForUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserPreferredJournals> getUserPreferredJournalsesForCreatedBy() {
        return userPreferredJournalsesForCreatedBy;
    }

    public void setUserPreferredJournalsesForCreatedBy(
            Set<UserPreferredJournals> userPreferredJournalsesForCreatedBy) {
        this.userPreferredJournalsesForCreatedBy = userPreferredJournalsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<UserSocietyDetails> getUserSocietyDetailsesForUpdatedBy() {
        return userSocietyDetailsesForUpdatedBy;
    }

    public void setUserSocietyDetailsesForUpdatedBy(
            Set<UserSocietyDetails> userSocietyDetailsesForUpdatedBy) {
        this.userSocietyDetailsesForUpdatedBy = userSocietyDetailsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserSocietyDetails> getUserSocietyDetailsesForCreatedBy() {
        return userSocietyDetailsesForCreatedBy;
    }

    public void setUserSocietyDetailsesForCreatedBy(
            Set<UserSocietyDetails> userSocietyDetailsesForCreatedBy) {
        this.userSocietyDetailsesForCreatedBy = userSocietyDetailsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<UserReferenceData> getUserReferenceDatasForCreatedBy() {
        return userReferenceDatasForCreatedBy;
    }

    public void setUserReferenceDatasForCreatedBy(
            Set<UserReferenceData> userReferenceDatasForCreatedBy) {
        this.userReferenceDatasForCreatedBy = userReferenceDatasForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUserId")
    public Set<UserRoles> getUserRolesesForUserId() {
        return userRolesesForUserId;
    }

    public void setUserRolesesForUserId(Set<UserRoles> userRolesesForUserId) {
        this.userRolesesForUserId = userRolesesForUserId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<AdditionalPermissions> getAdditionalPermissionsesForUpdatedBy() {
        return additionalPermissionsesForUpdatedBy;
    }

    public void setAdditionalPermissionsesForUpdatedBy(
            Set<AdditionalPermissions> additionalPermissionsesForUpdatedBy) {
        this.additionalPermissionsesForUpdatedBy = additionalPermissionsesForUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByCreatedBy")
    public Set<AdditionalPermissions> getAdditionalPermissionsesForCreatedBy() {
        return additionalPermissionsesForCreatedBy;
    }

    public void setAdditionalPermissionsesForCreatedBy(
            Set<AdditionalPermissions> additionalPermissionsesForCreatedBy) {
        this.additionalPermissionsesForCreatedBy = additionalPermissionsesForCreatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByUpdatedBy")
    public Set<ProfileAttributeList> getProfileAttributeListsForUpdatedBy() {
        return profileAttributeListsForUpdatedBy;
    }

    public void setProfileAttributeListsForUpdatedBy(
            Set<ProfileAttributeList> profileAttributeListsForUpdatedBy) {
        this.profileAttributeListsForUpdatedBy = profileAttributeListsForUpdatedBy;
    }

}
