package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/**
 * UserProfileAttribVisibleId generated by hbm2java
 */
@Embeddable
public class UserProfileAttribVisibleId implements java.io.Serializable {

    private Integer userId;
    private Character profileVisibilityFlg;
    private String profileAttribCd;
    private Date createdDate;
    private Integer createdBy;
    private Date updatedDate;
    private Integer updatedBy;

    public UserProfileAttribVisibleId() {
    }

    public UserProfileAttribVisibleId(Integer userId,
                                      Character profileVisibilityFlg, String profileAttribCd,
                                      Date createdDate, Integer createdBy, Date updatedDate,
                                      Integer updatedBy) {
        this.userId = userId;
        this.profileVisibilityFlg = profileVisibilityFlg;
        this.profileAttribCd = profileAttribCd;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updatedDate = updatedDate;
        this.updatedBy = updatedBy;
    }

    @Column(name = "USER_ID", precision = 22, scale = 0)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "PROFILE_VISIBILITY_FLG", length = 1)
    public Character getProfileVisibilityFlg() {
        return this.profileVisibilityFlg;
    }

    public void setProfileVisibilityFlg(Character profileVisibilityFlg) {
        this.profileVisibilityFlg = profileVisibilityFlg;
    }

    @Column(name = "PROFILE_ATTRIB_CD", length = 15)
    public String getProfileAttribCd() {
        return this.profileAttribCd;
    }

    public void setProfileAttribCd(String profileAttribCd) {
        this.profileAttribCd = profileAttribCd;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "CREATED_BY", precision = 22, scale = 0)
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Column(name = "UPDATED_BY", precision = 22, scale = 0)
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserProfileAttribVisibleId))
            return false;
        UserProfileAttribVisibleId castOther = (UserProfileAttribVisibleId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this
                .getUserId() != null && castOther.getUserId() != null && this
                .getUserId().equals(castOther.getUserId())))
                && ((this.getProfileVisibilityFlg() == castOther
                .getProfileVisibilityFlg()) || (this
                .getProfileVisibilityFlg() != null
                && castOther.getProfileVisibilityFlg() != null && this
                .getProfileVisibilityFlg().equals(
                        castOther.getProfileVisibilityFlg())))
                && ((this.getProfileAttribCd() == castOther
                .getProfileAttribCd()) || (this.getProfileAttribCd() != null
                && castOther.getProfileAttribCd() != null && this
                .getProfileAttribCd().equals(
                        castOther.getProfileAttribCd())))
                && ((this.getCreatedDate() == castOther.getCreatedDate()) || (this
                .getCreatedDate() != null
                && castOther.getCreatedDate() != null && this
                .getCreatedDate().equals(castOther.getCreatedDate())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
                .getCreatedBy() != null
                && castOther.getCreatedBy() != null && this
                .getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getUpdatedDate() == castOther.getUpdatedDate()) || (this
                .getUpdatedDate() != null
                && castOther.getUpdatedDate() != null && this
                .getUpdatedDate().equals(castOther.getUpdatedDate())))
                && ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this
                .getUpdatedBy() != null
                && castOther.getUpdatedBy() != null && this
                .getUpdatedBy().equals(castOther.getUpdatedBy())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37
                * result
                + (getProfileVisibilityFlg() == null ? 0 : this
                .getProfileVisibilityFlg().hashCode());
        result = 37
                * result
                + (getProfileAttribCd() == null ? 0 : this.getProfileAttribCd()
                .hashCode());
        result = 37
                * result
                + (getCreatedDate() == null ? 0 : this.getCreatedDate()
                .hashCode());
        result = 37 * result
                + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37
                * result
                + (getUpdatedDate() == null ? 0 : this.getUpdatedDate()
                .hashCode());
        result = 37 * result
                + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
        return result;
    }

}
