package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.Cascade;

import javax.persistence.*;
import java.util.Date;

/**
 * UserFunderGrants generated by hbm2java
 */
@Entity
@Table(name = "USER_FUNDER_GRANTS")
public class UserFunderGrants implements java.io.Serializable {

    private Integer userFunderGrantId;
    private ResearchFunders researchFunders;
    private Users usersByCreatedBy;
    private Users usersByUpdatedBy;
    private AuthorProfile authorProfile;
    private String grantNum;
    private Date createdDate;
    private Date updatedDate;

    public UserFunderGrants() {
    }

    public UserFunderGrants(Integer userFunderGrantId) {
        this.userFunderGrantId = userFunderGrantId;
    }

    public UserFunderGrants(Integer userFunderGrantId,
                            ResearchFunders researchFunders, Users usersByCreatedBy,
                            Users usersByUpdatedBy, AuthorProfile authorProfile,
                            String grantNum, Date createdDate, Date updatedDate) {
        this.userFunderGrantId = userFunderGrantId;
        this.researchFunders = researchFunders;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByUpdatedBy = usersByUpdatedBy;
        this.authorProfile = authorProfile;
        this.grantNum = grantNum;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "USER_FUNDER_GRANTS_SEQ")
    @SequenceGenerator(name = "USER_FUNDER_GRANTS_SEQ", sequenceName = "AS2APPUSER.USER_FUNDER_GRANTS_SEQ", allocationSize = 1)
    @Column(name = "USER_FUNDER_GRANT_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getUserFunderGrantId() {
        return this.userFunderGrantId;
    }

    public void setUserFunderGrantId(Integer userFunderGrantId) {
        this.userFunderGrantId = userFunderGrantId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RESFUNDERID")
    @Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE, org.hibernate.annotations.CascadeType.DELETE})
    public ResearchFunders getResearchFunders() {
        return this.researchFunders;
    }

    public void setResearchFunders(ResearchFunders researchFunders) {
        this.researchFunders = researchFunders;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY")
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }

    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPDATED_BY")
    public Users getUsersByUpdatedBy() {
        return this.usersByUpdatedBy;
    }

    public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
        this.usersByUpdatedBy = usersByUpdatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    public AuthorProfile getAuthorProfile() {
        return this.authorProfile;
    }

    public void setAuthorProfile(AuthorProfile authorProfile) {
        this.authorProfile = authorProfile;
    }

    @Column(name = "GRANT_NUM", length = 250)
    public String getGrantNum() {
        return this.grantNum;
    }

    public void setGrantNum(String grantNum) {
        this.grantNum = grantNum;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

}
