package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserProfileAttribVisibleId generated by hbm2java
 */
@Embeddable
public class UserProfileAttribVisibleId implements java.io.Serializable {

    private int userId;
    private String profileAttribCd;

    public UserProfileAttribVisibleId() {
    }

    public UserProfileAttribVisibleId(int userId, String profileAttribCd) {
        this.userId = userId;
        this.profileAttribCd = profileAttribCd;
    }

    @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "PROFILE_ATTRIB_CD", nullable = false, length = 15)
    public String getProfileAttribCd() {
        return profileAttribCd;
    }

    public void setProfileAttribCd(String profileAttribCd) {
        this.profileAttribCd = profileAttribCd;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof UserProfileAttribVisibleId)) {
            return false;
        }
        final UserProfileAttribVisibleId castOther = (UserProfileAttribVisibleId) other;

        return getUserId() == castOther.getUserId()
                && (getProfileAttribCd() == castOther.getProfileAttribCd() || getProfileAttribCd() != null
                        && castOther.getProfileAttribCd() != null
                        && getProfileAttribCd().equals(
                                castOther.getProfileAttribCd()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + getUserId();
        result = 37
                * result
                + (getProfileAttribCd() == null ? 0 : getProfileAttribCd()
                        .hashCode());
        return result;
    }

}
