package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserWoaAccountsId generated by hbm2java
 */
@Embeddable
public class UserWoaAccountsId implements java.io.Serializable {

    private int userId;
    private String woaInstitutionCd;

    public UserWoaAccountsId() {
    }

    public UserWoaAccountsId(int userId, String woaInstitutionCd) {
        this.userId = userId;
        this.woaInstitutionCd = woaInstitutionCd;
    }

    @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "WOA_INSTITUTION_CD", nullable = false, length = 15)
    public String getWoaInstitutionCd() {
        return woaInstitutionCd;
    }

    public void setWoaInstitutionCd(String woaInstitutionCd) {
        this.woaInstitutionCd = woaInstitutionCd;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof UserWoaAccountsId)) {
            return false;
        }
        final UserWoaAccountsId castOther = (UserWoaAccountsId) other;

        return getUserId() == castOther.getUserId()
                && (getWoaInstitutionCd() == castOther.getWoaInstitutionCd() || getWoaInstitutionCd() != null
                        && castOther.getWoaInstitutionCd() != null
                        && getWoaInstitutionCd().equals(
                                castOther.getWoaInstitutionCd()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + getUserId();
        result = 37
                * result
                + (getWoaInstitutionCd() == null ? 0 : getWoaInstitutionCd()
                        .hashCode());
        return result;
    }

}
