package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated Jul 7, 2015 5:39:57 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRolesId generated by hbm2java
 */
@Embeddable
public class UserRolesId implements java.io.Serializable {

    private int userId;
    private int roleId;

    public UserRolesId() {
    }

    public UserRolesId(int userId, int roleId) {
        this.userId = userId;
        this.roleId = roleId;
    }

    @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Column(name = "ROLE_ID", nullable = false, precision = 22, scale = 0)
    public int getRoleId() {
        return roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof UserRolesId)) {
            return false;
        }
        final UserRolesId castOther = (UserRolesId) other;

        return getUserId() == castOther.getUserId()
                && getRoleId() == castOther.getRoleId();
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + getUserId();
        result = 37 * result + getRoleId();
        return result;
    }

}
