package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatabasechangelogId generated by hbm2java
 */
@Embeddable
public class DatabasechangelogId implements java.io.Serializable {

	private String id;
	private String author;
	private String filename;
	private Date dateexecuted;
	private Integer orderexecuted;
	private String exectype;
	private String md5sum;
	private String description;
	private String comments;
	private String tag;
	private String liquibase;

	public DatabasechangelogId() {
	}

	public DatabasechangelogId(String id, String author, String filename,
			Date dateexecuted, Integer orderexecuted, String exectype) {
		this.id = id;
		this.author = author;
		this.filename = filename;
		this.dateexecuted = dateexecuted;
		this.orderexecuted = orderexecuted;
		this.exectype = exectype;
	}

	public DatabasechangelogId(String id, String author, String filename,
			Date dateexecuted, Integer orderexecuted, String exectype,
			String md5sum, String description, String comments, String tag,
			String liquibase) {
		this.id = id;
		this.author = author;
		this.filename = filename;
		this.dateexecuted = dateexecuted;
		this.orderexecuted = orderexecuted;
		this.exectype = exectype;
		this.md5sum = md5sum;
		this.description = description;
		this.comments = comments;
		this.tag = tag;
		this.liquibase = liquibase;
	}

	@Column(name = "ID", nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "AUTHOR", nullable = false)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "FILENAME", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "DATEEXECUTED", nullable = false)
	public Date getDateexecuted() {
		return this.dateexecuted;
	}

	public void setDateexecuted(Date dateexecuted) {
		this.dateexecuted = dateexecuted;
	}

	@Column(name = "ORDEREXECUTED", nullable = false, precision = 10, scale = 0)
	public Integer getOrderexecuted() {
		return this.orderexecuted;
	}

	public void setOrderexecuted(Integer orderexecuted) {
		this.orderexecuted = orderexecuted;
	}

	@Column(name = "EXECTYPE", nullable = false, length = 10)
	public String getExectype() {
		return this.exectype;
	}

	public void setExectype(String exectype) {
		this.exectype = exectype;
	}

	@Column(name = "MD5SUM", length = 35)
	public String getMd5sum() {
		return this.md5sum;
	}

	public void setMd5sum(String md5sum) {
		this.md5sum = md5sum;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "COMMENTS")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "TAG")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "LIQUIBASE", length = 20)
	public String getLiquibase() {
		return this.liquibase;
	}

	public void setLiquibase(String liquibase) {
		this.liquibase = liquibase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatabasechangelogId))
			return false;
		DatabasechangelogId castOther = (DatabasechangelogId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getAuthor() == castOther.getAuthor()) || (this
						.getAuthor() != null && castOther.getAuthor() != null && this
						.getAuthor().equals(castOther.getAuthor())))
				&& ((this.getFilename() == castOther.getFilename()) || (this
						.getFilename() != null
						&& castOther.getFilename() != null && this
						.getFilename().equals(castOther.getFilename())))
				&& ((this.getDateexecuted() == castOther.getDateexecuted()) || (this
						.getDateexecuted() != null
						&& castOther.getDateexecuted() != null && this
						.getDateexecuted().equals(castOther.getDateexecuted())))
				&& ((this.getOrderexecuted() == castOther.getOrderexecuted()) || (this
						.getOrderexecuted() != null
						&& castOther.getOrderexecuted() != null && this
						.getOrderexecuted()
						.equals(castOther.getOrderexecuted())))
				&& ((this.getExectype() == castOther.getExectype()) || (this
						.getExectype() != null
						&& castOther.getExectype() != null && this
						.getExectype().equals(castOther.getExectype())))
				&& ((this.getMd5sum() == castOther.getMd5sum()) || (this
						.getMd5sum() != null && castOther.getMd5sum() != null && this
						.getMd5sum().equals(castOther.getMd5sum())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getTag() == castOther.getTag()) || (this.getTag() != null
						&& castOther.getTag() != null && this.getTag().equals(
						castOther.getTag())))
				&& ((this.getLiquibase() == castOther.getLiquibase()) || (this
						.getLiquibase() != null
						&& castOther.getLiquibase() != null && this
						.getLiquibase().equals(castOther.getLiquibase())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getAuthor() == null ? 0 : this.getAuthor().hashCode());
		result = 37 * result
				+ (getFilename() == null ? 0 : this.getFilename().hashCode());
		result = 37
				* result
				+ (getDateexecuted() == null ? 0 : this.getDateexecuted()
						.hashCode());
		result = 37
				* result
				+ (getOrderexecuted() == null ? 0 : this.getOrderexecuted()
						.hashCode());
		result = 37 * result
				+ (getExectype() == null ? 0 : this.getExectype().hashCode());
		result = 37 * result
				+ (getMd5sum() == null ? 0 : this.getMd5sum().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		result = 37 * result
				+ (getLiquibase() == null ? 0 : this.getLiquibase().hashCode());
		return result;
	}

}
