package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvitationLog generated by hbm2java
 */
@Entity
@Table(name = "INVITATION_LOG")
public class InvitationLog implements java.io.Serializable {

	private Integer invitationId;
	private UserProfile userProfile;
	private Users users;
	private String emailAddr;
	private Integer articleId;
	private Date sentDate;

	public InvitationLog() {
	}

	public InvitationLog(Integer invitationId) {
		this.invitationId = invitationId;
	}

	public InvitationLog(Integer invitationId, UserProfile userProfile,
			Users users, String emailAddr, Integer articleId, Date sentDate) {
		this.invitationId = invitationId;
		this.userProfile = userProfile;
		this.users = users;
		this.emailAddr = emailAddr;
		this.articleId = articleId;
		this.sentDate = sentDate;
	}

	@Id
	@Column(name = "INVITATION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getInvitationId() {
		return this.invitationId;
	}

	public void setInvitationId(Integer invitationId) {
		this.invitationId = invitationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SENT_BY")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "EMAIL_ADDR", length = 250)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "ARTICLE_ID", precision = 22, scale = 0)
	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SENT_DATE", length = 7)
	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

}
