package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductRoles generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_ROLES")
public class ProductRoles implements java.io.Serializable {

	private String productRoleCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String productRoleName;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	private Set<ProductPersonRelations> productPersonRelationses = new HashSet<ProductPersonRelations>(
			0);

	public ProductRoles() {
	}

	public ProductRoles(String productRoleCd) {
		this.productRoleCd = productRoleCd;
	}

	public ProductRoles(String productRoleCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String productRoleName, String description,
			Date createdDate, Date updatedDate,
			Set<ProductPersonRelations> productPersonRelationses) {
		this.productRoleCd = productRoleCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.productRoleName = productRoleName;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.productPersonRelationses = productPersonRelationses;
	}

	@Id
	@Column(name = "PRODUCT_ROLE_CD", unique = true, nullable = false, length = 15)
	public String getProductRoleCd() {
		return this.productRoleCd;
	}

	public void setProductRoleCd(String productRoleCd) {
		this.productRoleCd = productRoleCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "PRODUCT_ROLE_NAME", length = 100)
	public String getProductRoleName() {
		return this.productRoleName;
	}

	public void setProductRoleName(String productRoleName) {
		this.productRoleName = productRoleName;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productRoles")
	public Set<ProductPersonRelations> getProductPersonRelationses() {
		return this.productPersonRelationses;
	}

	public void setProductPersonRelationses(
			Set<ProductPersonRelations> productPersonRelationses) {
		this.productPersonRelationses = productPersonRelationses;
	}

}
