package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SavedOrders generated by hbm2java
 */
@Entity
@Table(name = "SAVED_ORDERS")
public class SavedOrders implements java.io.Serializable {

    private Integer orderId;
    private Users usersByCreatedBy;
    private Users usersByUpdatedBy;
    private Products products;
    private Users usersByUserId;
    private String orderObject;
    private Date createdDate;
    private Date updatedDate;
    private Set<OrderArticleQuery> orderArticleQueries = new HashSet<OrderArticleQuery>(
            0);

    public SavedOrders() {
    }

    public SavedOrders(Integer orderId) {
        this.orderId = orderId;
    }

    public SavedOrders(Integer orderId, Users usersByCreatedBy,
            Users usersByUpdatedBy, Products products, Users usersByUserId,
            String orderObject, Date createdDate, Date updatedDate,
            Set<OrderArticleQuery> orderArticleQueries) {
        this.orderId = orderId;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByUpdatedBy = usersByUpdatedBy;
        this.products = products;
        this.usersByUserId = usersByUserId;
        this.orderObject = orderObject;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.orderArticleQueries = orderArticleQueries;
    }

    @Id
    @Column(name = "ORDER_ID", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SAVED_ORDERS_SEQ")
    @SequenceGenerator(name = "SAVED_ORDERS_SEQ", sequenceName = "SAVED_ORDERS_SEQ", allocationSize = 1)
    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY")
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }

    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPDATED_BY")
    public Users getUsersByUpdatedBy() {
        return this.usersByUpdatedBy;
    }

    public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
        this.usersByUpdatedBy = usersByUpdatedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DH_ID")
    public Products getProducts() {
        return this.products;
    }

    public void setProducts(Products products) {
        this.products = products;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }

    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }

    @Lob
    @Column(name = "ORDER_OBJECT")
    public String getOrderObject() {
        return this.orderObject;
    }

    @Lob
    public void setOrderObject(String orderObject) {
        this.orderObject = orderObject;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "savedOrders")
    public Set<OrderArticleQuery> getOrderArticleQueries() {
        return this.orderArticleQueries;
    }

    public void setOrderArticleQueries(
            Set<OrderArticleQuery> orderArticleQueries) {
        this.orderArticleQueries = orderArticleQueries;
    }

}
