package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserProfileAttribVisible generated by hbm2java
 */
@Entity
@Table(name = "USER_PROFILE_ATTRIB_VISIBLE")
public class UserProfileAttribVisible implements java.io.Serializable {

	private UserProfileAttribVisibleId id;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private UserProfile userProfile;
	private ProfileAttributeList profileAttributeList;
	private Character profileVisibilityFlg;
	private Date createdDate;
	private Date updatedDate;

	public UserProfileAttribVisible() {
	}

	public UserProfileAttribVisible(UserProfileAttribVisibleId id,
			UserProfile userProfile, ProfileAttributeList profileAttributeList) {
		this.id = id;
		this.userProfile = userProfile;
		this.profileAttributeList = profileAttributeList;
	}

	public UserProfileAttribVisible(UserProfileAttribVisibleId id,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			UserProfile userProfile, ProfileAttributeList profileAttributeList,
			Character profileVisibilityFlg, Date createdDate, Date updatedDate) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.userProfile = userProfile;
		this.profileAttributeList = profileAttributeList;
		this.profileVisibilityFlg = profileVisibilityFlg;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "profileAttribCd", column = @Column(name = "PROFILE_ATTRIB_CD", nullable = false, length = 15)) })
	public UserProfileAttribVisibleId getId() {
		return this.id;
	}

	public void setId(UserProfileAttribVisibleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFILE_ATTRIB_CD", nullable = false, insertable = false, updatable = false)
	public ProfileAttributeList getProfileAttributeList() {
		return this.profileAttributeList;
	}

	public void setProfileAttributeList(
			ProfileAttributeList profileAttributeList) {
		this.profileAttributeList = profileAttributeList;
	}

	@Column(name = "PROFILE_VISIBILITY_FLG", length = 1)
	public Character getProfileVisibilityFlg() {
		return this.profileVisibilityFlg;
	}

	public void setProfileVisibilityFlg(Character profileVisibilityFlg) {
		this.profileVisibilityFlg = profileVisibilityFlg;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
