package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 26, 2015 10:24:59 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WpgResponseDetails generated by hbm2java
 */
@Entity
@Table(name = "WPG_RESPONSE_DETAILS")
public class WpgResponseDetails implements java.io.Serializable {

	private WpgResponseDetailsId id;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;

	public WpgResponseDetails() {
	}

	public WpgResponseDetails(WpgResponseDetailsId id) {
		this.id = id;
	}

	public WpgResponseDetails(WpgResponseDetailsId id, Users usersByCreatedBy,
			Users usersByUpdatedBy) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "wpgLogId", column = @Column(name = "WPG_LOG_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "operation", column = @Column(name = "OPERATION", length = 50)),
			@AttributeOverride(name = "returnCode", column = @Column(name = "RETURN_CODE", precision = 22, scale = 0)),
			@AttributeOverride(name = "returnMessage", column = @Column(name = "RETURN_MESSAGE", length = 100)),
			@AttributeOverride(name = "vendorId", column = @Column(name = "VENDOR_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "transId", column = @Column(name = "TRANS_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "merchantResponse", column = @Column(name = "MERCHANT_RESPONSE", length = 100)),
			@AttributeOverride(name = "merchantId", column = @Column(name = "MERCHANT_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "cscResult", column = @Column(name = "CSC_RESULT", length = 1)),
			@AttributeOverride(name = "avsAddressResult", column = @Column(name = "AVS_ADDRESS_RESULT", length = 1)),
			@AttributeOverride(name = "avsPostResult", column = @Column(name = "AVS_POST_RESULT", length = 1)),
			@AttributeOverride(name = "token", column = @Column(name = "TOKEN", length = 25)),
			@AttributeOverride(name = "acquirerId", column = @Column(name = "ACQUIRER_ID", length = 1)),
			@AttributeOverride(name = "acquirerBank", column = @Column(name = "ACQUIRER_BANK", length = 25)),
			@AttributeOverride(name = "bankId", column = @Column(name = "BANK_ID", length = 1)),
			@AttributeOverride(name = "bankName", column = @Column(name = "BANK_NAME", length = 50)),
			@AttributeOverride(name = "maskedCardNumber", column = @Column(name = "MASKED_CARD_NUMBER", length = 25)),
			@AttributeOverride(name = "cardExpiry", column = @Column(name = "CARD_EXPIRY", precision = 22, scale = 0)),
			@AttributeOverride(name = "transTimestamp", column = @Column(name = "TRANS_TIMESTAMP")),
			@AttributeOverride(name = "security", column = @Column(name = "SECURITY", length = 50)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", precision = 22, scale = 0)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "UPDATED_DATE")),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "UPDATED_BY", precision = 22, scale = 0)) })
	public WpgResponseDetailsId getId() {
		return this.id;
	}

	public void setId(WpgResponseDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", insertable = false, updatable = false)
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY", insertable = false, updatable = false)
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

}
