package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/**
 * AuditDetailsId generated by hbm2java
 */
@Embeddable
public class AuditDetailsId implements java.io.Serializable {

	private Integer auditId;
	private String objName;
	private String objAttribute;
	private String actionCd;
	private String oldVal;
	private String newVal;
	private Integer userId;
	private Date createdDate;
	private Integer createdBy;

	public AuditDetailsId() {
	}

	public AuditDetailsId(Integer auditId, String objName, String objAttribute,
			String actionCd, String oldVal, String newVal, Integer userId,
			Date createdDate, Integer createdBy) {
		this.auditId = auditId;
		this.objName = objName;
		this.objAttribute = objAttribute;
		this.actionCd = actionCd;
		this.oldVal = oldVal;
		this.newVal = newVal;
		this.userId = userId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	@Column(name = "AUDIT_ID", precision = 22, scale = 0)
	public Integer getAuditId() {
		return this.auditId;
	}

	public void setAuditId(Integer auditId) {
		this.auditId = auditId;
	}

	@Column(name = "OBJ_NAME", length = 50)
	public String getObjName() {
		return this.objName;
	}

	public void setObjName(String objName) {
		this.objName = objName;
	}

	@Column(name = "OBJ_ATTRIBUTE", length = 50)
	public String getObjAttribute() {
		return this.objAttribute;
	}

	public void setObjAttribute(String objAttribute) {
		this.objAttribute = objAttribute;
	}

	@Column(name = "ACTION_CD", length = 15)
	public String getActionCd() {
		return this.actionCd;
	}

	public void setActionCd(String actionCd) {
		this.actionCd = actionCd;
	}

	@Column(name = "OLD_VAL", length = 250)
	public String getOldVal() {
		return this.oldVal;
	}

	public void setOldVal(String oldVal) {
		this.oldVal = oldVal;
	}

	@Column(name = "NEW_VAL", length = 250)
	public String getNewVal() {
		return this.newVal;
	}

	public void setNewVal(String newVal) {
		this.newVal = newVal;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", precision = 22, scale = 0)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditDetailsId))
			return false;
		AuditDetailsId castOther = (AuditDetailsId) other;

		return ((this.getAuditId() == castOther.getAuditId()) || (this
				.getAuditId() != null && castOther.getAuditId() != null && this
				.getAuditId().equals(castOther.getAuditId())))
				&& ((this.getObjName() == castOther.getObjName()) || (this
						.getObjName() != null && castOther.getObjName() != null && this
						.getObjName().equals(castOther.getObjName())))
				&& ((this.getObjAttribute() == castOther.getObjAttribute()) || (this
						.getObjAttribute() != null
						&& castOther.getObjAttribute() != null && this
						.getObjAttribute().equals(castOther.getObjAttribute())))
				&& ((this.getActionCd() == castOther.getActionCd()) || (this
						.getActionCd() != null
						&& castOther.getActionCd() != null && this
						.getActionCd().equals(castOther.getActionCd())))
				&& ((this.getOldVal() == castOther.getOldVal()) || (this
						.getOldVal() != null && castOther.getOldVal() != null && this
						.getOldVal().equals(castOther.getOldVal())))
				&& ((this.getNewVal() == castOther.getNewVal()) || (this
						.getNewVal() != null && castOther.getNewVal() != null && this
						.getNewVal().equals(castOther.getNewVal())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this
						.getCreatedDate() != null
						&& castOther.getCreatedDate() != null && this
						.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
						.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this
						.getCreatedBy().equals(castOther.getCreatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAuditId() == null ? 0 : this.getAuditId().hashCode());
		result = 37 * result
				+ (getObjName() == null ? 0 : this.getObjName().hashCode());
		result = 37
				* result
				+ (getObjAttribute() == null ? 0 : this.getObjAttribute()
						.hashCode());
		result = 37 * result
				+ (getActionCd() == null ? 0 : this.getActionCd().hashCode());
		result = 37 * result
				+ (getOldVal() == null ? 0 : this.getOldVal().hashCode());
		result = 37 * result
				+ (getNewVal() == null ? 0 : this.getNewVal().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37
				* result
				+ (getCreatedDate() == null ? 0 : this.getCreatedDate()
						.hashCode());
		result = 37 * result
				+ (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		return result;
	}

}
