package com.wiley.gr.ace.sharedservices.persistence.entity;
// default package
// Generated Jun 23, 2015 4:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuthColleagueDetails generated by hbm2java
 */
@Entity
@Table(name = "AUTH_COLLEAGUE_DETAILS")
public class AuthColleagueDetails implements java.io.Serializable {

	private Integer authColleagueId;
	private UserProfile userProfileByColleagueUserId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private UserProfile userProfileByInvitedAuthorId;
	private String firstName;
	private String lastName;
	private String emailAddr;
	private Integer assignedArticleId;
	private Date createdDate;
	private Date updatedDate;

	public AuthColleagueDetails() {
	}

	public AuthColleagueDetails(Integer authColleagueId) {
		this.authColleagueId = authColleagueId;
	}

	public AuthColleagueDetails(Integer authColleagueId,
			UserProfile userProfileByColleagueUserId, Users usersByCreatedBy,
			Users usersByUpdatedBy, UserProfile userProfileByInvitedAuthorId,
			String firstName, String lastName, String emailAddr,
			Integer assignedArticleId, Date createdDate, Date updatedDate) {
		this.authColleagueId = authColleagueId;
		this.userProfileByColleagueUserId = userProfileByColleagueUserId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.userProfileByInvitedAuthorId = userProfileByInvitedAuthorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddr = emailAddr;
		this.assignedArticleId = assignedArticleId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "AUTH_COLLEAGUE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getAuthColleagueId() {
		return this.authColleagueId;
	}

	public void setAuthColleagueId(Integer authColleagueId) {
		this.authColleagueId = authColleagueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLLEAGUE_USER_ID")
	public UserProfile getUserProfileByColleagueUserId() {
		return this.userProfileByColleagueUserId;
	}

	public void setUserProfileByColleagueUserId(
			UserProfile userProfileByColleagueUserId) {
		this.userProfileByColleagueUserId = userProfileByColleagueUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVITED_AUTHOR_ID")
	public UserProfile getUserProfileByInvitedAuthorId() {
		return this.userProfileByInvitedAuthorId;
	}

	public void setUserProfileByInvitedAuthorId(
			UserProfile userProfileByInvitedAuthorId) {
		this.userProfileByInvitedAuthorId = userProfileByInvitedAuthorId;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ADDR", length = 100)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "ASSIGNED_ARTICLE_ID", precision = 22, scale = 0)
	public Integer getAssignedArticleId() {
		return this.assignedArticleId;
	}

	public void setAssignedArticleId(Integer assignedArticleId) {
		this.assignedArticleId = assignedArticleId;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
