package com.wiley.gr.ace.sharedservices.persistence.entity;
// default package
// Generated Jun 23, 2015 4:17:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAreaOfInterestId generated by hbm2java
 */
@Embeddable
public class UserAreaOfInterestId implements java.io.Serializable {

    private Integer userId;
    private String areaOfInterestCd;

    public UserAreaOfInterestId() {
    }

    public UserAreaOfInterestId(Integer userId, String areaOfInterestCd) {
        this.userId = userId;
        this.areaOfInterestCd = areaOfInterestCd;
    }

    @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "AREA_OF_INTEREST_CD", nullable = false, length = 15)
    public String getAreaOfInterestCd() {
        return this.areaOfInterestCd;
    }

    public void setAreaOfInterestCd(String areaOfInterestCd) {
        this.areaOfInterestCd = areaOfInterestCd;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserAreaOfInterestId))
            return false;
        UserAreaOfInterestId castOther = (UserAreaOfInterestId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this
                .getUserId() != null && castOther.getUserId() != null && this
                .getUserId().equals(castOther.getUserId())))
                && ((this.getAreaOfInterestCd() == castOther
                .getAreaOfInterestCd()) || (this.getAreaOfInterestCd() != null
                && castOther.getAreaOfInterestCd() != null && this
                .getAreaOfInterestCd().equals(
                        castOther.getAreaOfInterestCd())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37
                * result
                + (getAreaOfInterestCd() == null ? 0 : this
                .getAreaOfInterestCd().hashCode());
        return result;
    }

}
