package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserSecondaryEmailAddr generated by hbm2java
 */
@Entity
@Table(name = "USER_SECONDARY_EMAIL_ADDR")
public class UserSecondaryEmailAddr implements java.io.Serializable {

	private Integer userSecondaryEmailId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Users usersByUserId;
	private String secondaryEmailAddr;
	private Date createdDate;
	private Date updatedDate;
	private Set<AuthorProfile> authorProfiles = new HashSet<AuthorProfile>(0);

	public UserSecondaryEmailAddr() {
	}

	public UserSecondaryEmailAddr(Integer userSecondaryEmailId) {
		this.userSecondaryEmailId = userSecondaryEmailId;
	}

	public UserSecondaryEmailAddr(Integer userSecondaryEmailId,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			Users usersByUserId, String secondaryEmailAddr, Date createdDate,
			Date updatedDate, Set<AuthorProfile> authorProfiles) {
		this.userSecondaryEmailId = userSecondaryEmailId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.usersByUserId = usersByUserId;
		this.secondaryEmailAddr = secondaryEmailAddr;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.authorProfiles = authorProfiles;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="USER_SECONDARY_EMAIL_ADDR_SEQ")
	@SequenceGenerator(name="USER_SECONDARY_EMAIL_ADDR_SEQ",sequenceName="AS2APPUSER.USER_SECONDARY_EMAIL_ADDR_SEQ",allocationSize=1)
	@Column(name = "USER_SECONDARY_EMAIL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUserSecondaryEmailId() {
		return this.userSecondaryEmailId;
	}

	public void setUserSecondaryEmailId(Integer userSecondaryEmailId) {
		this.userSecondaryEmailId = userSecondaryEmailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	@Column(name = "SECONDARY_EMAIL_ADDR", length = 256)
	public String getSecondaryEmailAddr() {
		return this.secondaryEmailAddr;
	}

	public void setSecondaryEmailAddr(String secondaryEmailAddr) {
		this.secondaryEmailAddr = secondaryEmailAddr;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userSecondaryEmailAddr")
	public Set<AuthorProfile> getAuthorProfiles() {
		return this.authorProfiles;
	}

	public void setAuthorProfiles(Set<AuthorProfile> authorProfiles) {
		this.authorProfiles = authorProfiles;
	}

}
