package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * UserProfileAttribVisible generated by hbm2java
 */
@Entity
@Table(name = "USER_PROFILE_ATTRIB_VISIBLE")
public class UserProfileAttribVisible implements java.io.Serializable {

	private UserProfileAttribVisibleId id;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;
	private ProfileAttributeList profileAttributeList;

	public UserProfileAttribVisible() {
	}

	public UserProfileAttribVisible(UserProfileAttribVisibleId id) {
		this.id = id;
	}

	public UserProfileAttribVisible(UserProfileAttribVisibleId id,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			AuthorProfile authorProfile,
			ProfileAttributeList profileAttributeList) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
		this.profileAttributeList = profileAttributeList;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "profileVisibilityFlg", column = @Column(name = "PROFILE_VISIBILITY_FLG", length = 1)),
			@AttributeOverride(name = "profileAttribCd", column = @Column(name = "PROFILE_ATTRIB_CD", length = 15)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", precision = 22, scale = 0)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "UPDATED_DATE")),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "UPDATED_BY", precision = 22, scale = 0)) })
	public UserProfileAttribVisibleId getId() {
		return this.id;
	}

	public void setId(UserProfileAttribVisibleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY", insertable = false, updatable = false)
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY", insertable = false, updatable = false)
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", insertable = false, updatable = false)
	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFILE_ATTRIB_CD", insertable = false, updatable = false)
	public ProfileAttributeList getProfileAttributeList() {
		return this.profileAttributeList;
	}

	public void setProfileAttributeList(
			ProfileAttributeList profileAttributeList) {
		this.profileAttributeList = profileAttributeList;
	}

}
