package com.wiley.gr.ace.sharedservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.Cascade;

import javax.persistence.*;
import java.util.Date;

/**
 * UserAreaOfInterest generated by hbm2java
 */
@Entity
@Table(name = "USER_AREA_OF_INTEREST")
public class UserAreaOfInterest implements java.io.Serializable {

	private UserAreaOfInterestId id;
	private AreaOfInterest areaOfInterest;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;
	private Date createdDate;
	private Date updatedDate;

	public UserAreaOfInterest() {
	}

	public UserAreaOfInterest(UserAreaOfInterestId id,
			AreaOfInterest areaOfInterest, AuthorProfile authorProfile) {
		this.id = id;
		this.areaOfInterest = areaOfInterest;
		this.authorProfile = authorProfile;
	}

	public UserAreaOfInterest(UserAreaOfInterestId id,
			AreaOfInterest areaOfInterest, Users usersByCreatedBy,
			Users usersByUpdatedBy, AuthorProfile authorProfile,
			Date createdDate, Date updatedDate) {
		this.id = id;
		this.areaOfInterest = areaOfInterest;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "areaOfInterestCd", column = @Column(name = "AREA_OF_INTEREST_CD", nullable = false, length = 15)) })
	public UserAreaOfInterestId getId() {
		return this.id;
	}

	public void setId(UserAreaOfInterestId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AREA_OF_INTEREST_CD", nullable = false, insertable = false, updatable = false)
	@Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE, org.hibernate.annotations.CascadeType.DELETE})
	public AreaOfInterest getAreaOfInterest() {
		return this.areaOfInterest;
	}

	public void setAreaOfInterest(AreaOfInterest areaOfInterest) {
		this.areaOfInterest = areaOfInterest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
